import { Skeleton } from 'src/components/feedback/Skeleton/Skeleton'
import { type Meta, type StoryObj } from '@storybook/react'

const meta: Meta<typeof Skeleton> = {
  title: 'Components/Feedback/Skeleton',
  component: props => <Skeleton {...props} style={{ height: '200px', width: '200px' }}></Skeleton>,

  args: {
    loading: true,
    paragraph: false,
    title: false,
  },
}
export default meta

type Story = StoryObj<typeof Skeleton>

/*
  Initial story templates generated by AI.
  Customize the stories based on specific requirements.
*/

export const Primary: Story = {
  args: {
    paragraph: true,
  },
}
