import { type Meta } from '@storybook/react'
import { type StoryObj } from '@storybook/react'
import { Alert } from 'src/components/feedback/Alert/Alert'

const meta: Meta<typeof Alert> = {
  title: 'Components/Feedback/Alert',
  component: Alert,

  args: {
    banner: false,
    showIcon: false,
    type: 'info',
    onClose: e => {
      alert('Alert On Close')
    },
    afterClose: () => {
      console.log('Alert After Closed')
    },
  },
  argTypes: {
    type: {
      control: 'select',
      options: ['success', 'info', 'warning', 'error'],
    },
  },
}
export default meta

type Story = StoryObj<typeof Alert>

/*
  Initial story templates generated by AI.
  Customize the stories based on specific requirements.
*/

export const Info: Story = {
  args: {
    type: 'info',
    message: 'Note',
    description: 'Audience size estimates are approximate.',
  },
}

export const Success: Story = {
  args: {
    type: 'success',
    closable: true,
    message: 'The predictive attribute has been successfully created and now is being calculated.',
  },
}

export const Warning: Story = {
  args: {
    message: 'The default environment is Production.',
    description:
      "Ensure your audience's environment aligns with that of any parent audiences to avoid unexpected results.",
    type: 'warning',
    showIcon: true,
    closable: true,
  },
}

export const Error: Story = {
  args: {
    message: 'An error occurred creating the tracing configuration',
    type: 'error',
    showIcon: false,
  },
}
