import { type Meta } from '@storybook/react'
import { type StoryObj } from '@storybook/react'
import { Alert } from 'src/components/feedback/Alert/Alert'
import { Flex } from 'src/components/layout/Flex/Flex'
import { Typography } from 'src/components/general/Typography/Typography'
import { ColorWhite, ColorBorderSecondary, BorderRadiusLg, SizeXs } from 'src/styles/style'

const meta: Meta<typeof Alert> = {
  title: 'Components/Feedback/Alert',
  component: Alert,

  args: {
    banner: false,
    showIcon: false,
    type: 'info',
    onClose: e => {
      alert('Alert On Close')
    },
    afterClose: () => {
      console.log('Alert After Closed')
    },
  },
  argTypes: {
    type: {
      control: 'select',
      options: ['success', 'info', 'warning', 'error'],
    },
  },
}
export default meta

type Story = StoryObj<typeof Alert>

/*
  Initial story templates generated by AI.
  Customize the stories based on specific requirements.
*/

export const StorybookNote: Story = {
  render: () => {
    return (
      <Alert
        message={
          <Flex align="center" gap={SizeXs}>
            <Typography.Text size="xl">💡</Typography.Text>
            <Typography.Text size="base">
              Use the{' '}
              <Typography.Link href="?path=/docs/components-feedback-message--docs" underline>
                Message component
              </Typography.Link>{' '}
              if the notification should dismiss automatically.
            </Typography.Text>
          </Flex>
        }
        showIcon={false}
        type="info"
        style={{
          backgroundColor: ColorWhite,
          border: `1px solid ${ColorBorderSecondary}`,
          borderRadius: BorderRadiusLg,
          width: '100%',
          marginBottom: 0,
        }}
      />
    )
  },
}

export const Info: Story = {
  args: {
    type: 'info',
    message: 'This is an informational message.',
    showIcon: true,
    style: { marginBottom: 0, width: '600px' },
  },
}

export const Success: Story = {
  args: {
    type: 'success',
    message: 'This is a success message.',
    showIcon: true,
    style: { marginBottom: 0, width: '600px' },
  },
}

export const Warning: Story = {
  args: {
    message: 'This is a warning message.',
    type: 'warning',
    showIcon: true,
    style: { marginBottom: 0, width: '600px' },
  },
}

export const Error: Story = {
  args: {
    message: 'This is an error message.',
    type: 'error',
    showIcon: true,
    style: { marginBottom: 0, width: '600px' },
  },
}

export const InfoWithoutIcon: Story = {
  args: {
    type: 'info',
    message: 'This is an informational message.',
    showIcon: false,
    style: { marginBottom: 0, width: '600px' },
  },
}

export const ErrorWithoutIcon: Story = {
  args: {
    message: 'An error occurred creating the tracing configuration',
    type: 'error',
    showIcon: false,
    style: { marginBottom: 0, width: '600px' },
  },
}

export const ErrorWithExpandCollapse: Story = {
  args: {
    type: 'error',
    expandable: true,
    closable: true,
    message: 'This is an error message.',
    expandableContent: <Typography.Text size="base">Error details go here</Typography.Text>,
    style: { marginBottom: 0, width: '600px' },
  },
}

export const WithCloseButton: Story = {
  args: {
    type: 'warning',
    message: 'This is a warning message.',
    showIcon: true,
    closable: true,
    style: { marginBottom: 0, width: '600px' },
  },
}
