import { type Meta, type StoryObj } from '@storybook/react'

import { Card } from 'src/components/data-display/Card/Card'
import { Button } from 'src/components'

const meta: Meta<typeof Card> = {
  title: 'Aquarium/Data Display/Card',
  component: props => <Card {...props}>{props.children}</Card>,

  args: {
    actions: undefined,
    activeTabKey: undefined,
    bodyStyle: undefined,
    bordered: true,
    cover: undefined,
    defaultActiveTabKey: undefined,
    extra: undefined,
    headStyle: undefined,
    hoverable: false,
    loading: false,
    size: 'default',
    tabBarExtraContent: undefined,
    tabList: undefined,
    tabProps: undefined,
    title: 'Card Title',
    type: undefined,
    children: 'Card Content',
    onTabChange: key => {
      alert(`Tab Changed: ${key}`)
    },
  },
  argTypes: {
    size: {
      control: 'select',
      options: ['default', 'small'],
    },
  },
}
export default meta

type Story = StoryObj<typeof Card>

/*
  Initial story templates generated by AI.
  Customize the stories based on specific requirements.
*/

export const Primary: Story = {}

export const SmallSize: Story = {
  args: {
    size: 'small',
  },
}

export const NoBorder: Story = {
  args: {
    bordered: false,
  },
}

export const Hoverable: Story = {
  args: {
    hoverable: true,
  },
}

export const Loading: Story = {
  args: {
    loading: true,
  },
}

export const WithActions: Story = {
  args: {
    children:'Custom Actions',
    actions: [
      <Button key="edit">Edit</Button>,
    ],
  },
}

export const WithTabs: Story = {
  args: {
    tabList: [
      { key: 'tab1', tab: 'Tab 1' },
      { key: 'tab2', tab: 'Tab 2' },
      { key: 'tab3', tab: 'Tab 3' },
    ],
  },
}

export const WithCover: Story = {
  args: {
    cover: <img alt="example" src="https://example.com/cover.jpg" />,
  },
}

export const CustomTitle: Story = {
  args: {
    title: <Button>Any React Component</Button>,
  },
}

export const InnerStyle: Story = {
  args: {
    type: 'inner',
  },
}