import {
  Blue4,
  Blue8,
  ColorTextDescription,
  ColorTextLabel,
  ColorTextSecondary,
  Cyan4,
  Cyan8,
  Gold1,
  Gold3,
  Gold4,
  Gold7,
  Gold8,
  Green1,
  Green3,
  Green7,
  Lime4,
  Lime8,
  Magenta4,
  Magenta5,
  Magenta7,
  Magenta8,
  MpBrandSecondary6,
  MpBrandSecondary8,
  MpBrandSecondary9,
  Purple4,
  Purple7,
  Purple8,
  Volcano4,
  Volcano8,
} from 'src/styles/style'

export const FutureEventsChartColors = {
  gridLine: 'rgba(0, 0, 0, 0.05)',
  userBinFill: 'rgba(22, 119, 255, 0.08)',
  userBinFillHover: 'rgba(22, 119, 255, 0.32)',
  userBinBorder: 'rgba(22, 119, 255, 0.16)',
  cvrLine: Magenta5,
  cvrLineMarker: Magenta7,
  rangeFill: 'rgba(95, 41, 248, 0.20)',
  rangeBorder: Purple7,
  averageLine: MpBrandSecondary6,
  averageLineLabel: ColorTextLabel,
  liftPositiveBg: Green1,
  liftPositiveBorder: Green3,
  liftPositiveText: Green7,
  liftNegativeBg: Gold1,
  liftNegativeBorder: Gold3,
  liftNegativeText: Gold7,
  defaultTextColor: ColorTextSecondary,
} as const

export const NBAChartColors = {
  defaultTextColor: ColorTextSecondary,
  cvrLine: MpBrandSecondary6,
  cvrLineMarker: MpBrandSecondary8,
  rangeFill: 'rgba(95, 41, 248, 0.20)',
  rangeBorder: Purple7,
  actionPalette: [
    Blue4,
    Cyan4,
    Gold4,
    Volcano4,
    Magenta4,
    Purple4,
    Lime4,
    Lime8,
    Cyan8,
    Blue8,
    Purple8,
    Magenta8,
    Volcano8,
    Gold8,
  ],
} as const

export const SimilarCustomersChartColors = {
  gridLine: 'rgba(0, 0, 0, 0.05)',
  defaultTextColor: ColorTextDescription,
  dissimilarBand: '#E9EAEB80',
  moderatelySimilarBand: '#ACDC7980',
  mostSimilarBand: '#2ED3B780',
  selectedRangeBorder: Purple7,
  selectedRangeFill: 'rgba(95, 41, 248, 0.20)',
  predictedSimilarityLine: MpBrandSecondary6,
  predictedSimilarityMarker: MpBrandSecondary9,
  avgLine: MpBrandSecondary6,
  avgLineLabel: ColorTextLabel,
} as const
