import { type Meta, type StoryObj } from '@storybook/react'
import { Pagination } from 'src/components/navigation/Pagination/Pagination'
import { ExampleStory } from 'src/utils/ExampleStory'

const meta: Meta<typeof Pagination> = {
  title: 'Components/Not Prod Ready/Navigation/Pagination',
  component: Pagination,

  args: {
    current: 1,
    defaultCurrent: 1,
    defaultPageSize: 10,
    pageSize: 10,
    pageSizeOptions: [10, 20, 50, 100],
    onChange: (page, pageSize) => {
      alert(`Page changed to ${page}, Page Size: ${pageSize}`)
    },
    onShowSizeChange: (current, size) => {
      alert(`Page Size changed to ${size}, Current Page: ${current}`)
    },
  },
}
export default meta

type Story = StoryObj<typeof Pagination>

/*
  Initial story templates generated by AI.
  Customize the stories based on specific requirements.
*/

export const Default: Story = {
  render: () => {
    return (
      <ExampleStory title="">
        <Pagination defaultCurrent={1} pageSize={40} total={500} />
      </ExampleStory>
    )
  },
}
