import { type Meta } from '@storybook/react'
import { type StoryObj } from '@storybook/react'
import { Space } from 'src/components'
import { Link } from 'src/components/general/Typography/Typography'
import { ExampleStory } from 'src/utils/ExampleStory'

const meta: Meta<typeof Link> = {
  title: 'Aquarium/General/Link',
  component: props => <Link {...props}>Example Link</Link>,

  args: {
    code: false,
    copyable: false,
    delete: false,
    disabled: false,
    editable: false,
    ellipsis: false,
    keyboard: false,
    mark: false,
    strong: false,
    italic: false,
    type: undefined,
    underline: false,
    onClick: (event: React.MouseEvent) => {
      console.log('Link Clicked')
    },
  },
  argTypes: {
    type: {
      control: 'select',
      options: ['secondary', 'success', 'warning', 'danger'],
    },
  },
}
export default meta

type Story = StoryObj<typeof Link>

/*
  Initial story templates generated by AI.
  Customize the stories based on specific requirements.
*/

export const Primary: Story = {}

export const Code: Story = {
  args: {
    code: true,
  },
}

export const Copyable: Story = {
  args: {
    copyable: true,
  },
}

export const Deleted: Story = {
  args: {
    delete: true,
  },
}

export const Disabled: Story = {
  args: {
    disabled: true,
  },
}

export const Editable: Story = {
  args: {
    editable: true,
  },
}

export const Keyboard: Story = {
  args: {
    keyboard: true,
  },
}

export const Marked: Story = {
  args: {
    mark: true,
  },
}

export const Strong: Story = {
  args: {
    strong: true,
  },
}

export const Italic: Story = {
  args: {
    italic: true,
  },
}

export const Success: Story = {
  args: {
    type: 'success',
  },
}

export const Secondary: Story = {
  args: {
    type: 'secondary',
  },
}

export const Warning: Story = {
  args: {
    type: 'warning',
  },
}

export const Danger: Story = {
  args: {
    type: 'danger',
  },
}

export const Underline: Story = {
  args: {
    underline: true,
  },
}

export const CustomOnClick: Story = {
  args: {
    onClick: event => {
      alert('Custom Click Handler')
    },
  },
}

export const ExampleLinks: Story = {
  render: () => {
    return (
      <ExampleStory title={<> </>}>
        <Space direction="vertical">
          <Link>Ant Design (default)</Link>
          <Link type="secondary">Ant Design (secondary)</Link>
          <Link type="success">Ant Design (success)</Link>
          <Link type="warning">Ant Design (warning)</Link>
          <Link type="danger">Ant Design (danger)</Link>
          <Link disabled>Ant Design (disabled)</Link>
          <Link mark>Ant Design (mark)</Link>
          <Link code>Ant Design (code)</Link>
          <Link keyboard>Ant Design (keyboard)</Link>
          <Link underline>Ant Design (underline)</Link>
          <Link delete>Ant Design (delete)</Link>
          <Link strong>Ant Design (strong)</Link>
          <Link italic>Ant Design (italic)</Link>
        </Space>
      </ExampleStory>
    )
  },
}