import type { Meta } from '@storybook/react'
import type { StoryObj } from '@storybook/react'
import { Alert, Flex, Icon, Tooltip } from 'src/components'
import { Typography } from 'src/components/general/Typography/Typography'
import { TypographyColors } from './colors'
import { SizeXs } from 'src/styles/style'

const meta: Meta<typeof Typography.Link> = {
  title: 'Components/General/Typography/Link',
  component: Typography.Link,

  args: {
    children: 'Example Text',
    type: undefined,
    color: undefined,
    size: 'base',
    code: false,
    copyable: false,
    delete: false,
    disabled: false,
    editable: false,
    ellipsis: false,
    mark: false,
    strong: false,
    italic: false,
    underline: false,
  },
  argTypes: {
    children: {
      control: 'text',
      name: 'text',
    },
    type: {
      control: 'select',
      options: ['secondary', 'success', 'warning', 'danger'],
    },
    size: {
      control: 'select',
      options: ['base', 'sm', 'lg', 'xl'],
    },
    color: {
      control: 'select',
      options: TypographyColors,
    },
    copyable: {
      control: 'boolean',
    },
    delete: {
      control: 'boolean',
    },
    disabled: {
      control: 'boolean',
    },
    editable: {
      control: 'boolean',
    },
    ellipsis: {
      control: 'boolean',
    },
    mark: {
      control: 'boolean',
    },
    strong: {
      control: 'boolean',
    },
    italic: {
      control: 'boolean',
    },
    code: {
      control: 'boolean',
    },
  },
}
export default meta

type Story = StoryObj<typeof Typography.Link>

/*
  Initial story templates generated by AI.
  Customize the stories based on specific requirements.
*/

export const Primary: Story = {
  args: {
    underline: true,
  },
}

export const InsideTooltip: Story = {
  render: () => {
    return (
      <Tooltip
        title={
          <>
            <Typography.Text tooltip>
              Help lorem ipsum{' '}
              <Typography.Link href="/" tooltip>
                Learn More
              </Typography.Link>
            </Typography.Text>
          </>
        }>
        <Icon name="help" size="sm" />
      </Tooltip>
    )
  },
}

export const LongDescription: Story = {
  render: () => {
    return (
      <Typography.Paragraph color="ColorTextDescription">
        This is placeholder descriptive copy that illustrates how inline links sit alongside supporting content. The
        paragraph spacing demonstrates how the link remains readable even within longer bodies of narrative.{' '}
        <Typography.Link
          href="https://mparticle.com/docs"
          color="ColorTextDescription"
          underline
          target="_blank"
          rel="noopener noreferrer">
          Explore the documentation
        </Typography.Link>{' '}
        to learn more about this topic. Keep the surrounding text concise and focused so the call to action is easy to
        scan. When possible, avoid stacking multiple links within the same sentence to maintain clarity.
      </Typography.Paragraph>
    )
  },
}

export const WithInlineIcon: Story = {
  render: () => {
    return (
      <Typography.Link
        underline
        target="_blank"
        rel="noopener noreferrer"
        href="https://docs.mparticle.com/"
        color="ColorLink">
        <Flex align="center" gap={SizeXs}>
          <span>View documentation</span>
          <Icon name="openTab" size="sm" color="primary" />
        </Flex>
      </Typography.Link>
    )
  },
}

export const WithoutUnderline: Story = {
  render: () => {
    return (
      <Typography.Link underline={false} href="https://docs.mparticle.com/" target="_blank" rel="noopener noreferrer">
        Example Text
      </Typography.Link>
    )
  },
}

export const InsideErrorAlert: Story = {
  render: () => {
    return (
      <Alert
        type="error"
        showIcon
        message={
          <Typography.Text color="ColorText">
            Something went wrong.{' '}
            <Typography.Link color="ColorText" underline href="https://mparticle.com/support">
              Contact support
            </Typography.Link>{' '}
            to get help.
          </Typography.Text>
        }
      />
    )
  },
}
