import type { Meta } from '@storybook/react'
import type { StoryObj } from '@storybook/react'
import { Flex, Icon, Space, Tooltip } from 'src/components'
import { Typography } from 'src/components/general/Typography/Typography'
import { ExampleStory } from 'src/utils/ExampleStory'
import { TypographyColors } from './colors'

const meta: Meta<typeof Typography.Link> = {
  title: 'Components/General/Typography/Link',
  component: props => <Typography.Link {...props}>Example Link</Typography.Link>,

  args: {
    children: 'Example Text',
    type: undefined,
    color: undefined,
    size: 'base',
    code: false,
    copyable: false,
    delete: false,
    disabled: false,
    editable: false,
    ellipsis: false,
    mark: false,
    strong: false,
    italic: false,
    underline: false,
  },
  argTypes: {
    children: {
      control: 'text',
      name: 'text',
    },
    type: {
      control: 'select',
      options: ['secondary', 'success', 'warning', 'danger'],
    },
    size: {
      control: 'select',
      options: ['base', 'sm', 'lg', 'xl'],
    },
    color: {
      control: 'select',
      options: TypographyColors,
    },
    copyable: {
      control: 'boolean',
    },
    delete: {
      control: 'boolean',
    },
    disabled: {
      control: 'boolean',
    },
    editable: {
      control: 'boolean',
    },
    ellipsis: {
      control: 'boolean',
    },
    mark: {
      control: 'boolean',
    },
    strong: {
      control: 'boolean',
    },
    italic: {
      control: 'boolean',
    },
    code: {
      control: 'boolean',
    },
  },
}
export default meta

type Story = StoryObj<typeof Typography.Link>

/*
  Initial story templates generated by AI.
  Customize the stories based on specific requirements.
*/

export const Primary: Story = {}

export const InsideTooltip: Story = {
  render: () => {
    return (
      <ExampleStory title="Link inside a Tooltip">
        <Flex align="center" gap={2}>
          <Typography.Text>Typography inside of a tooltip, hover icon to see</Typography.Text>
          <Tooltip
            title={
              <>
                <Typography.Text tooltip>
                  Help lorem ipsum{' '}
                  <Typography.Link href="/" tooltip>
                    Learn More
                  </Typography.Link>
                </Typography.Text>
              </>
            }>
            <Icon name="help" size="sm" />
          </Tooltip>
        </Flex>
      </ExampleStory>
    )
  },
}

export const ExampleLinks: Story = {
  render: () => {
    return (
      <ExampleStory title={<> </>}>
        <Space direction="vertical">
          <Typography.Link>Ant Design (default)</Typography.Link>
          <Typography.Link type="secondary">Ant Design (secondary)</Typography.Link>
          <Typography.Link type="success">Ant Design (success)</Typography.Link>
          <Typography.Link type="warning">Ant Design (warning)</Typography.Link>
          <Typography.Link type="danger">Ant Design (danger)</Typography.Link>
          <Typography.Link disabled>Ant Design (disabled)</Typography.Link>
          <Typography.Link mark>Ant Design (mark)</Typography.Link>
          <Typography.Link code>Ant Design (code)</Typography.Link>
          <Typography.Link keyboard>Ant Design (keyboard)</Typography.Link>
          <Typography.Link underline>Ant Design (underline)</Typography.Link>
          <Typography.Link delete>Ant Design (delete)</Typography.Link>
          <Typography.Link strong>Ant Design (strong)</Typography.Link>
          <Typography.Link italic>Ant Design (italic)</Typography.Link>
        </Space>
      </ExampleStory>
    )
  },
}
