import {
  AddIcon,
  AlicornIcon,
  AnalyticsIconDt,
  C360IconDt,
  CatalogIcon,
  ChartColumnIcon,
  ChartLineIcon,
  CheckIcon,
  CircleNodesIcon,
  CloudIcon,
  ConnectionsIcon,
  DataPlatformIconDt,
  DatabaseIcon,
  DsrIcon,
  EmptyIcon,
  EnrichmentIcon,
  EventAttributeIcon,
  EventIcon,
  FitToScreen,
  FolderClosedIcon,
  ForwardingIcon,
  GearIcon,
  GridIcon,
  HeartIcon,
  HelpIcon,
  IdentityIcon,
  JumpToIcon,
  LightBulbIcon,
  LiveStreamIcon,
  PaywallIcon,
  MessageQuestionIcon,
  MpLogoIcon,
  ObservabilityIcon,
  OversightIconDt,
  PredictionsIcon,
  RemoveIcon,
  SearchIcon,
  SegmentationIconDt,
  ShieldKeyholeIcon,
  SignoutIcon,
  SplitIcon,
  SystemAlertsIcon,
  TransformationsIcon,
  UploadIcon,
  UserAttributeIcon,
  UserProfilesIcon,
  UsersIcon,
  WrenchIcon,
  ZoomIn,
  ZoomOut,
  PremiumIcon,
  HelpVideoIcon,
  ConversionIcon,
  PredictionsIconDt,
  NextIcon,
  PreviousIcon,
  OpenTabIcon,
  DirectoryIcon,
  LockIcon,
  UnlockIcon,
  NotificationIcon,
} from 'src/components/icons'

/**
 * @deprecated This icon is old
 * Use this icon only for legacy purposes. This will be removed once all icons are updated.
 */
const SparklesIcon = PredictionsIcon
export const icons = [
  { name: 'add', component: AddIcon, variant: 'light', category: 'general' },
  { name: 'alicorn', component: AlicornIcon, variant: 'light', category: 'general' },
  { name: 'analytics', component: AnalyticsIconDt, variant: 'duo-tone', category: 'pm' },
  { name: 'c360', component: C360IconDt, variant: 'duo-tone', category: 'pm' },
  { name: 'catalog', component: CatalogIcon, variant: 'light', category: 'pm' },
  { name: 'chartColumn', component: ChartColumnIcon, variant: 'light', category: 'general' },
  { name: 'chartLine', component: ChartLineIcon, variant: 'light', category: 'general' },
  { name: 'check', component: CheckIcon, variant: 'light', category: 'general' },
  { name: 'circleNodes', component: CircleNodesIcon, variant: 'light', category: 'general' },
  { name: 'cloud', component: CloudIcon, variant: 'light', category: 'general' },
  { name: 'connections', component: ConnectionsIcon, variant: 'light', category: 'general' },
  { name: 'dataPlatform', component: DataPlatformIconDt, variant: 'duo-tone', category: 'pm' },
  { name: 'database', component: DatabaseIcon, variant: 'light', category: 'general' },
  { name: 'dsr', component: DsrIcon, variant: 'light', category: 'pm' },
  { name: 'empty', component: EmptyIcon, variant: 'light', category: 'general' },
  { name: 'enrichment', component: EnrichmentIcon, variant: 'light', category: 'pm' },
  { name: 'eventAttribute', component: EventAttributeIcon, variant: 'light', category: 'general' },
  { name: 'event', component: EventIcon, variant: 'light', category: 'general' },
  { name: 'fitToScreen', component: FitToScreen, variant: 'light', category: 'general' },
  { name: 'folderClosed', component: FolderClosedIcon, variant: 'light', category: 'general' },
  { name: 'forwarding', component: ForwardingIcon, variant: 'light', category: 'pm' },
  { name: 'gear', component: GearIcon, variant: 'light', category: 'general' },
  { name: 'grid', component: GridIcon, variant: 'light', category: 'general' },
  { name: 'heart', component: HeartIcon, variant: 'light', category: 'general' },
  { name: 'help', component: HelpIcon, variant: 'light', category: 'general' },
  { name: 'identity', component: IdentityIcon, variant: 'light', category: 'pm' },
  { name: 'jumpTo', component: JumpToIcon, variant: 'light', category: 'general' },
  { name: 'lightBulb', component: LightBulbIcon, variant: 'light', category: 'general' },
  { name: 'liveStream', component: LiveStreamIcon, variant: 'light', category: 'pm' },
  { name: 'paywall', component: PaywallIcon, variant: 'light', category: 'general' },
  { name: 'messageQuestion', component: MessageQuestionIcon, variant: 'light', category: 'general' },
  { name: 'mpLogo', component: MpLogoIcon, variant: 'light', category: 'general' },
  { name: 'observability', component: ObservabilityIcon, variant: 'light', category: 'pm' },
  { name: 'oversight', component: OversightIconDt, variant: 'duo-tone', category: 'pm' },
  { name: 'sparkles', component: SparklesIcon, variant: 'light', category: 'general' },
  { name: 'predictions', component: PredictionsIcon, variant: 'light', category: 'general' },
  { name: 'predictions', component: PredictionsIconDt, variant: 'duo-tone', category: 'general' },
  { name: 'remove', component: RemoveIcon, variant: 'light', category: 'general' },
  { name: 'search', component: SearchIcon, variant: 'light', category: 'general' },
  { name: 'segmentation', component: SegmentationIconDt, variant: 'duo-tone', category: 'pm' },
  { name: 'shieldKeyhole', component: ShieldKeyholeIcon, variant: 'light', category: 'general' },
  { name: 'signout', component: SignoutIcon, variant: 'light', category: 'general' },
  { name: 'split', component: SplitIcon, variant: 'light', category: 'general' },
  { name: 'systemAlerts', component: SystemAlertsIcon, variant: 'light', category: 'pm' },
  { name: 'transformations', component: TransformationsIcon, variant: 'light', category: 'pm' },
  { name: 'upload', component: UploadIcon, variant: 'light', category: 'general' },
  { name: 'userAttribute', component: UserAttributeIcon, variant: 'light', category: 'general' },
  { name: 'userProfiles', component: UserProfilesIcon, variant: 'light', category: 'pm' },
  { name: 'users', component: UsersIcon, variant: 'light', category: 'general' },
  { name: 'wrench', component: WrenchIcon, variant: 'light', category: 'general' },
  { name: 'zoomIn', component: ZoomIn, variant: 'light', category: 'general' },
  { name: 'zoomOut', component: ZoomOut, variant: 'light', category: 'general' },
  { name: 'premium', component: PremiumIcon, variant: 'light', category: 'general' },
  { name: 'helpVideo', component: HelpVideoIcon, variant: 'light', category: 'general' },
  { name: 'conversion', component: ConversionIcon, variant: 'light', category: 'general' },
  { name: 'next', component: NextIcon, variant: 'light', category: 'general' },
  { name: 'previous', component: PreviousIcon, variant: 'light', category: 'general' },
  { name: 'openTab', component: OpenTabIcon, variant: 'light', category: 'general' },
  { name: 'directory', component: DirectoryIcon, variant: 'light', category: 'general' },
  { name: 'lock', component: LockIcon, variant: 'light', category: 'general' },
  { name: 'unlock', component: UnlockIcon, variant: 'light', category: 'general' },
  { name: 'notification', component: NotificationIcon, variant: 'light', category: 'general' },
]
