import {
  AddIcon,
  AlicornIcon,
  AnalyticsIcon,
  CatalogIcon,
  ChartColumnIcon,
  ChartLineIcon,
  CheckIcon,
  CircleNodesIcon,
  CloudIcon,
  ConnectionsIcon,
  DatabaseIcon,
  DsrIcon,
  EmptyIcon,
  EnrichmentIcon,
  EventAttributeIcon,
  EventIcon,
  FolderClosedIcon,
  ForwardingIcon,
  GearIcon,
  GridIcon,
  HeartIcon,
  HelpIcon,
  IdentityIcon,
  JumpToIcon,
  LightBulbIcon,
  LiveStreamIcon,
  LockIcon,
  MessageQuestionIcon,
  MpLogoIcon,
  ObservabilityIcon,
  RemoveIcon,
  ShieldKeyholeIcon,
  SignoutIcon,
  SiteMapIcon,
  SparklesIcon,
  SplitIcon,
  SystemAlertsIcon,
  TransformationsIcon,
  UserAttributeIcon,
  UserProfileIcon,
  UsersIcon,
  WrenchIcon,
} from 'src/components/icons'

export const Icons = {
  add: AddIcon,
  alicorn: AlicornIcon,
  analytics: AnalyticsIcon,
  catalog: CatalogIcon,
  chartColumn: ChartColumnIcon,
  chartLine: ChartLineIcon,
  check: CheckIcon,
  circleNodes: CircleNodesIcon,
  cloud: CloudIcon,
  connections: ConnectionsIcon,
  database: DatabaseIcon,
  dsr: DsrIcon,
  empty: EmptyIcon,
  enrichment: EnrichmentIcon,
  event: EventIcon,
  eventAttribute: EventAttributeIcon,
  folderClosed: FolderClosedIcon,
  forwarding: ForwardingIcon,
  gear: GearIcon,
  grid: GridIcon,
  heart: HeartIcon,
  help: HelpIcon,
  identity: IdentityIcon,
  jumpTo: JumpToIcon,
  lightBulb: LightBulbIcon,
  liveStream: LiveStreamIcon,
  lock: LockIcon,
  messageQuestion: MessageQuestionIcon,
  mpLogo: MpLogoIcon,
  observability: ObservabilityIcon,
  remove: RemoveIcon,
  shieldKeyhole: ShieldKeyholeIcon,
  signout: SignoutIcon,
  siteMap: SiteMapIcon,
  sparkles: SparklesIcon,
  split: SplitIcon,
  systemAlerts: SystemAlertsIcon,
  transformation: TransformationsIcon,
  userAttribute: UserAttributeIcon,
  userProfile: UserProfileIcon,
  users: UsersIcon,
  wrench: WrenchIcon,
} as const
