import { Button } from 'src/components/general/Button/Button'
import { type Meta, type StoryObj } from '@storybook/react'
import { userEvent } from '@storybook/test'
import { Alert, Dropdown, Flex, Icon, Typography, Tooltip } from 'src/components'
import React from 'react'
import type { MenuProps } from 'antd'
import { BorderRadiusLg, ColorBorderSecondary, ColorWhite, MarginMd, SizeXs } from 'src/styles/style'

const meta: Meta<typeof Button> = {
  title: 'Components/General/Button',
  component: props => <Button {...props}>{props.children ?? 'Button Label'}</Button>,

  args: {
    danger: false,
    disabled: false,
    ghost: false,
    loading: false,
    shape: 'default',
    size: 'middle',
    type: 'primary',
  },

  argTypes: {
    shape: {
      control: 'select',
      options: ['default', 'circle', 'round'],
    },
    size: {
      control: 'select',
      options: ['small', 'middle', 'large'],
    },
    type: {
      control: 'select',
      options: ['primary', 'dashed', 'link', 'text', 'default'],
    },
  },
}
export default meta

type Story = StoryObj<typeof Button>
export const LinkUsageNote: Story = {
  parameters: {
    docs: {
      source: {
        state: 'hidden',
      },
    },
  },
  render: () => {
    return (
      <Alert
        type="info"
        showIcon={false}
        style={{
          backgroundColor: ColorWhite,
          border: `1px solid ${ColorBorderSecondary}`,
          borderRadius: BorderRadiusLg,
          width: '100%',
          marginBottom: 0,
        }}
        message={
          <Flex align="center" gap={SizeXs}>
            <Typography.Text size="xl">💡</Typography.Text>
            <Typography.Text size="base">
              Use the{' '}
              <Typography.Link
                href="https://mparticle.github.io/aquarium/?path=/story/components-general-typography-link--primary"
                underline>
                Typography.Link
              </Typography.Link>{' '}
              when navigating to a new URL or external page.
            </Typography.Text>
          </Flex>
        }
      />
    )
  },
}

/*
  Initial story templates generated by AI.
  Customize the stories based on specific requirements.
*/

export const Primary: Story = {
  args: {
    type: 'primary',
    children: 'Primary',
  },
  play: async context => {
    const button = context.canvasElement.querySelector('button')
    if (button) {
      await userEvent.click(button) // Click the button
    } else {
      throw new Error('Button not found')
    }
  },
}

export const PrimaryWithIcon: Story = {
  args: {
    type: 'primary',
    icon: <Icon name="add" size="sm" />,
    children: 'Primary',
  },
}

export const Default: Story = {
  args: {
    type: 'default',
    children: 'Secondary',
  },
}

export const DefaultWithIcon: Story = {
  args: {
    type: 'default',
    icon: <Icon size="sm" name="transformation" />,
    children: 'Secondary',
  },
}

export const Dashed: Story = {
  args: {
    type: 'dashed',
    children: 'Tertiary',
  },
}

export const DashedWithIcon: Story = {
  args: {
    type: 'dashed',
    icon: <Icon size="sm" name="add" />,
    children: 'Tertiary',
  },
}

export const Link: Story = {
  args: {
    type: 'link',
    children: 'Link',
  },
}

export const LinkWithIcon: Story = {
  args: {
    type: 'link',
    icon: <Icon name="add" />,
    children: 'Link',
  },
}

export const Text: Story = {
  args: {
    type: 'text',
    children: 'Text',
  },
}

export const Danger: Story = {
  args: {
    type: 'default',
    danger: true,
    children: 'Delete',
  },
}

export const Loading: Story = {
  args: {
    type: 'primary',
    loading: true,
    children: 'Loading',
  },
}

export const LoadingText: Story = {
  args: {
    type: 'text',
    loading: true,
    children: 'Load more',
  },
}

export const TypesOverview: Story = {
  render: () => {
    return (
      <Flex wrap gap={MarginMd} align="center">
        <Button type="primary">Primary</Button>
        <Button type="default">Secondary</Button>
        <Button type="dashed">Tertiary</Button>
        <Button type="text">Text</Button>
        <Button type="link">Link</Button>
      </Flex>
    )
  },
}

export const IconTypesOverview: Story = {
  render: () => {
    return (
      <Flex wrap gap={MarginMd} align="center">
        <Button type="primary" icon={<Icon name="add" size="sm" />}>
          Primary
        </Button>
        <Button type="default" icon={<Icon name="add" size="sm" />}>
          Secondary
        </Button>
        <Button type="dashed" icon={<Icon name="add" size="sm" />}>
          Tertiary
        </Button>
        <Button type="text" icon={<Icon name="add" size="sm" />}>
          Text
        </Button>
        <Button type="link" icon={<Icon name="add" size="sm" />}>
          Link
        </Button>
      </Flex>
    )
  },
}

export const SizeExamples: Story = {
  render: () => {
    return (
      <Flex gap={MarginMd} align="center">
        <Button type="default" size="small">
          Small
        </Button>
        <Button type="default">Default</Button>
        <Button type="default" size="large">
          Large
        </Button>
      </Flex>
    )
  },
}

export const IconOnly: Story = {
  render: () => {
    return (
      <Flex wrap gap={MarginMd} align="center">
        <Button type="primary" icon={<Icon name="add" />} aria-label="Primary action" />
        <Button type="default" icon={<Icon name="add" />} aria-label="Secondary action" />
        <Button type="dashed" icon={<Icon name="add" />} aria-label="Tertiary action" />
        <Button type="text" icon={<Icon name="add" />} aria-label="Refresh" />
        <Button type="link" icon={<Icon name="add" />} aria-label="Navigate" />
      </Flex>
    )
  },
}

export const Refresh: Story = {
  render: () => {
    return (
      <>
        <Flex gap="small" align="center">
          <Tooltip title="Fetch new data from the server">
            <Button type="text" icon={<Icon name="refresh" size="sm" color="text" />}>
              Refresh
            </Button>
          </Tooltip>

          <Tooltip title="Refresh and fetch latest data">
            <Button type="text" icon={<Icon name="refresh" size="sm" color="strong" />} />
          </Tooltip>
        </Flex>
      </>
    )
  },
}

export const With2Options: Story = {
  render: () => {
    const refreshMenu: MenuProps = {
      items: [
        {
          key: 'refresh-columns',
          label: 'Refresh Columns',
        },
        {
          key: 'refresh-values',
          label: 'Refresh Values',
        },
      ],
      onClick: ({ key }) => {
        console.log('Selected:', key)
      },
    }

    return (
      <Dropdown menu={refreshMenu}>
        <Button icon={<Icon name="refresh" size="sm" />}>
          <Typography.Text>Refresh Now</Typography.Text>
        </Button>
      </Dropdown>
    )
  },
}

export const LinkColorInheritance: Story = {
  render: () => {
    return (
      <Flex vertical gap={MarginMd}>
        <div style={{ color: '#52c41a' }}>
          <Typography.Text>Button link inside green text container:</Typography.Text>
          <Button type="link" color="inherit">
            Inherits Green Color
          </Button>
        </div>

        <div style={{ color: '#ff4d4f' }}>
          <Typography.Text>Button link inside red text container:</Typography.Text>
          <Button type="link" color="inherit">
            Inherits Red Color
          </Button>
        </div>

        <div style={{ color: '#1677ff' }}>
          <Typography.Text>Button link inside blue text container:</Typography.Text>
          <Button type="link" color="inherit">
            Inherits Blue Color
          </Button>
        </div>

        <Typography.Text type="secondary">
          Without color prop (uses default link color):
          <Button type="link">Default Link Color</Button>
        </Typography.Text>
      </Flex>
    )
  },
}
