import { Button } from 'src/components/general/Button/Button'
import { type Meta, type StoryObj } from '@storybook/react'
import { userEvent } from 'storybook/test'
import { Alert, Dropdown, Flex, Icon, Typography, Tooltip } from 'src/components'
import React from 'react'
import type { MenuProps } from 'antd'
import { BorderRadiusLg, ColorBorderSecondary, ColorWhite, MarginMd, SizeXs } from 'src/styles/style'
import { RoktPlus, RoktSearch, RoktEdit, RoktTrash } from 'src/components/icons'

const meta: Meta<typeof Button> = {
  title: 'Components/General/Button',
  component: props => <Button {...props}>{props.children ?? 'Button Label'}</Button>,

  args: {
    danger: false,
    disabled: false,
    ghost: false,
    loading: false,
    shape: 'default',
    size: 'middle',
    type: 'primary',
  },

  argTypes: {
    shape: {
      control: 'select',
      options: ['default', 'circle', 'round'],
    },
    size: {
      control: 'select',
      options: ['small', 'middle', 'large'],
    },
    type: {
      control: 'select',
      options: ['primary', 'dashed', 'link', 'text', 'default'],
    },
  },
}
export default meta

type Story = StoryObj<typeof Button>
export const LinkUsageNote: Story = {
  parameters: {
    docs: {
      source: {
        state: 'hidden',
      },
    },
  },
  render: () => {
    return (
      <Alert
        type="info"
        showIcon={false}
        style={{
          backgroundColor: ColorWhite,
          border: `1px solid ${ColorBorderSecondary}`,
          borderRadius: BorderRadiusLg,
          width: '100%',
          marginBottom: 0,
        }}
        message={
          <Flex align="center" gap={SizeXs}>
            <Typography.Text size="xl">💡</Typography.Text>
            <Typography.Text size="base">
              Use the{' '}
              <Typography.Link
                href="https://mparticle.github.io/aquarium/?path=/story/components-general-typography-link--primary"
                color="ColorText">
                Typography.Link
              </Typography.Link>{' '}
              when navigating to a new URL or external page.
            </Typography.Text>
          </Flex>
        }
      />
    )
  },
}

/*
  Initial story templates generated by AI.
  Customize the stories based on specific requirements.
*/

export const Primary: Story = {
  args: {
    type: 'primary',
    children: 'Primary',
  },
  play: async context => {
    const button = context.canvasElement.querySelector('button')
    if (button) {
      await userEvent.click(button) // Click the button
    } else {
      throw new Error('Button not found')
    }
  },
}

export const PrimaryWithIcon: Story = {
  args: {
    type: 'primary',
    icon: <Icon name="add" size="sm" />,
    children: 'Primary',
  },
}

export const Default: Story = {
  args: {
    type: 'default',
    children: 'Secondary',
  },
}

export const DefaultWithIcon: Story = {
  args: {
    type: 'default',
    icon: <Icon size="sm" name="transformation" />,
    children: 'Secondary',
  },
}

export const Dashed: Story = {
  args: {
    type: 'dashed',
    children: 'Tertiary',
  },
}

export const DashedWithIcon: Story = {
  args: {
    type: 'dashed',
    icon: <Icon size="sm" name="add" />,
    children: 'Tertiary',
  },
}

export const Link: Story = {
  args: {
    type: 'link',
    children: 'Link',
  },
}

export const LinkWithIcon: Story = {
  args: {
    type: 'link',
    icon: <Icon name="add" />,
    children: 'Link',
  },
}

export const Text: Story = {
  args: {
    type: 'text',
    children: 'Text',
  },
}

export const Danger: Story = {
  args: {
    type: 'default',
    danger: true,
    children: 'Delete',
  },
}

export const Loading: Story = {
  args: {
    type: 'primary',
    loading: true,
    children: 'Loading',
  },
}

export const LoadingText: Story = {
  args: {
    type: 'text',
    loading: true,
    children: 'Load more',
  },
}

export const TypesOverview: Story = {
  render: () => {
    return (
      <Flex wrap gap={MarginMd} align="center">
        <Button type="primary">Primary</Button>
        <Button type="default">Secondary</Button>
        <Button type="dashed">Tertiary</Button>
        <Button type="text">Text</Button>
        <Button type="link">Link</Button>
      </Flex>
    )
  },
}

export const DarkButton: Story = {
  render: () => {
    return (
      <Flex wrap gap={MarginMd} align="center">
        <Button color="default" variant="solid">
          Dark
        </Button>
        <Button color="default" variant="solid" icon={<Icon name="add" size="sm" />}>
          Dark with Icon
        </Button>
        <Button color="default" variant="solid" disabled>
          Dark Disabled
        </Button>
      </Flex>
    )
  },
}

export const IconTypesOverview: Story = {
  render: () => {
    return (
      <Flex wrap gap={MarginMd} align="center">
        <Button type="primary" icon={<Icon name="add" size="sm" />}>
          Primary
        </Button>
        <Button type="default" icon={<Icon name="add" size="sm" />}>
          Secondary
        </Button>
        <Button type="dashed" icon={<Icon name="add" size="sm" />}>
          Tertiary
        </Button>
        <Button type="text" icon={<Icon name="add" size="sm" />}>
          Text
        </Button>
        <Button type="link" icon={<Icon name="add" size="sm" />}>
          Link
        </Button>
      </Flex>
    )
  },
}

export const SizeExamples: Story = {
  render: () => {
    return (
      <Flex gap={MarginMd} align="center">
        <Button type="default" size="small">
          Small
        </Button>
        <Button type="default">Default</Button>
        <Button type="default" size="large">
          Large
        </Button>
      </Flex>
    )
  },
}

export const IconOnly: Story = {
  render: () => {
    return (
      <Flex wrap gap={MarginMd} align="center">
        <Button type="primary" icon={<Icon name="add" />} aria-label="Primary action" />
        <Button type="default" icon={<Icon name="add" />} aria-label="Secondary action" />
        <Button type="dashed" icon={<Icon name="add" />} aria-label="Tertiary action" />
        <Button type="text" icon={<Icon name="add" />} aria-label="Refresh" />
        <Button type="link" icon={<Icon name="add" />} aria-label="Navigate" />
      </Flex>
    )
  },
}

export const Refresh: Story = {
  render: () => {
    return (
      <>
        <Flex gap="small" align="center">
          <Tooltip title="Fetch new data from the server">
            <Button type="text" icon={<Icon name="refresh" size="sm" color="text" />}>
              Refresh
            </Button>
          </Tooltip>

          <Tooltip title="Refresh and fetch latest data">
            <Button type="text" icon={<Icon name="refresh" size="sm" color="strong" />} />
          </Tooltip>
        </Flex>
      </>
    )
  },
}

export const With2Options: Story = {
  render: () => {
    const refreshMenu: MenuProps = {
      items: [
        {
          key: 'refresh-columns',
          label: 'Refresh Columns',
        },
        {
          key: 'refresh-values',
          label: 'Refresh Values',
        },
      ],
      onClick: ({ key }) => {
        console.log('Selected:', key)
      },
    }

    return (
      <Dropdown menu={refreshMenu}>
        <Button icon={<Icon name="refresh" size="sm" />}>
          <Typography.Text>Refresh Now</Typography.Text>
        </Button>
      </Dropdown>
    )
  },
}

// Buttons with local icons
export const ButtonsWithLocalIcons: Story = {
  render: () => {
    return (
      <Flex gap="middle" align="center" wrap="wrap">
        <Button type="primary" icon={<Icon name="add" size="sm" />}>
          Add Item
        </Button>
        <Button type="default" icon={<Icon name="edit" size="sm" />}>
          Edit
        </Button>
        <Button type="default" danger icon={<Icon name="delete" size="sm" />}>
          Delete
        </Button>
      </Flex>
    )
  },
}

// Buttons with Rokt/Untitled UI icons
export const ButtonsWithUntitledUIIcons: Story = {
  render: () => {
    return (
      <Flex gap="middle" align="center" wrap="wrap">
        <Button type="primary" icon={<Icon name={RoktPlus} size="sm" />}>
          Add Item
        </Button>
        <Button type="default" icon={<Icon name={RoktEdit} size="sm" />}>
          Edit
        </Button>
        <Button type="default" danger icon={<Icon name={RoktTrash} size="sm" />}>
          Delete
        </Button>
      </Flex>
    )
  },
}

// Rokt/Untitled UI Icons Integration Demo
export const WithUntitledUIIcons: Story = {
  render: () => {
    return (
      <Flex vertical gap="large">
        <div>
          <Typography.Title level={4}>Buttons with Rokt/Untitled UI Icons</Typography.Title>
        </div>

        <div>
          <Typography.Title level={5}>Action Buttons</Typography.Title>
          <Flex wrap gap={MarginMd} align="center">
            <Button type="primary" icon={<Icon name={RoktPlus} size="sm" />}>
              Add Item
            </Button>
            <Button type="default" icon={<Icon name={RoktSearch} size="sm" />}>
              Search
            </Button>
            <Button type="default" icon={<Icon name={RoktEdit} size="sm" />}>
              Edit
            </Button>
            <Button type="default" danger icon={<Icon name={RoktTrash} size="sm" />}>
              Delete
            </Button>
          </Flex>
        </div>

        <div>
          <Typography.Title level={5}>Icon-Only Buttons</Typography.Title>
          <Flex wrap gap={MarginMd} align="center">
            <Tooltip title="Add new item">
              <Button type="primary" icon={<Icon name={RoktPlus} size="sm" />} />
            </Tooltip>
            <Tooltip title="Search">
              <Button type="default" icon={<Icon name={RoktSearch} size="sm" />} />
            </Tooltip>
            <Tooltip title="Edit">
              <Button type="default" icon={<Icon name={RoktEdit} size="sm" />} />
            </Tooltip>
            <Tooltip title="Delete">
              <Button type="default" danger icon={<Icon name={RoktTrash} size="sm" />} />
            </Tooltip>
          </Flex>
        </div>
      </Flex>
    )
  },
}
