import { type Meta, type StoryObj } from '@storybook/react'
import { Space } from 'src/components'
import { Notification } from 'src/components/feedback/Notification/Notification'
import { Button } from 'src/components/general/Button/Button'
import { FontWeightStrong } from 'src/styles/style'

const meta: Meta<typeof Notification> = {
  title: 'Components/Feedback/Notification',
  component: Notification,

  args: {
    children: <Button type="primary">Show Notification</Button>,
    message: 'Message',
    description: 'Description goes here',
    duration: 0,
    btn: undefined,
    key: undefined,
    placement: 'topRight',
    role: 'alert',
    onClick: function () {
      alert('Notification Clicked')
    },
    onClose: function () {
      alert('Notification Closed')
    },
  },
  argTypes: {
    role: {
      control: 'select',
      options: ['alert', 'status'],
    },
    type: {
      control: 'select',
      options: ['info', 'warning', 'success', 'error'],
    },
  },
}
export default meta

type Story = StoryObj<typeof Notification>

/*
  Initial story templates generated by AI.
  Customize the stories based on specific requirements.
*/

export const Primary: Story = {
  args: {
    placement: 'bottomLeft',
    message: <span style={{ fontWeight: FontWeightStrong }}>Join the new mParticle Experience!</span>,
    description:
      'Managing your data is easier than ever with the new mParticle experience. Try out the latest features with ease, and switch back to the classic experience anytime from the side navigation.',
    btn: (
      <Space>
        <Button type="link" size="small">
          Remind me later
        </Button>
        <Button type="primary" size="small">
          Take me there
        </Button>
      </Space>
    ),
  },
}
