import { Meta } from "@storybook/react";
import { StoryObj } from "@storybook/react";
import { FloatButton } from "src/components/general/FloatButton/FloatButton";

const meta: Meta<typeof FloatButton> = {
  title: "Aquarium/General/FloatButton",
  component: FloatButton,

  args: {
    // icon: <IconComponent />,
    description: "Float Button",
    tooltip: "Tooltip Text",
    type: "primary",
    shape: "circle",
    href: "",
    target: "",
    badge: undefined,
    onClick: (event) => alert("Float Button Clicked!"),
  },
};
export default meta;


type Story = StoryObj<typeof FloatButton>

/*
  Initial story templates generated by AI.
  Customize the stories based on specific requirements.
*/

export const Primary: Story = {
  args: {},
};

export const WithBadge: Story = {
  args: {
    badge: { count: 5 },
  },
};

export const Square: Story = {
  args: {
    shape: "square",
  },
};