import { Meta } from "@storybook/react";
import { StoryObj } from "@storybook/react";
import { Space } from "src/components/layout/Space/Space";
import { Divider } from "src/components/layout/Divider/Divider";
import { Button } from "src/components/general/Button/Button";

const meta: Meta<typeof Space> = {
  title: "Aquarium/Layout/Space",
  component: props => <>
    <Space {...props}>
      Text A
      <Button>Button</Button>
      Text B
    </Space>
  </>,

  args: {
    align: undefined,
    direction: "horizontal",
    size: "small",
    wrap: false,
  },

  argTypes: {
    align: {
      control: "select",
      options: ["start", "end", "center", "baseline"],
    },
    direction: {
      control: "select",
      options: ["vertical", "horizontal"],
    },
  },
};
export default meta;


type Story = StoryObj<typeof Space>


/*
  Initial story templates generated by AI.
  Customize the stories based on specific requirements.
*/

export const Primary: Story = {};

export const VerticalSpace: Story = {
  args: {
    direction: "vertical",
  },
};

export const LargeSizeSpace: Story = {
  args: {
    size: "large",
  },
};

export const SplitSpace: Story = {
  args: {
    split: <Divider/>,
  },
};

export const WrappedSpace: Story = {
  args: {
    wrap: true,
  },
};

export const CenterAlignedSpace: Story = {
  args: {
    align: "center",
  },
};

export const EndAlignedSpace: Story = {
  args: {
    align: "end",
  },
};

export const HorizontalSpaceWithSplit: Story = {
  args: {
    direction: "horizontal",
    split: <Divider/>,
  },
};