import type { RequireAtLeastOne } from 'type-fest'

export const ICON_VARIANTS = {
  LIGHT: 'light',
  DUO_TONE: 'duo-tone',
} as const

export type IconVariant = (typeof ICON_VARIANTS)[keyof typeof ICON_VARIANTS]

export type IconOptions = RequireAtLeastOne<
  {
    [ICON_VARIANTS.LIGHT]?: React.ComponentType<React.SVGProps<SVGSVGElement>>
    [ICON_VARIANTS.DUO_TONE]?: React.ComponentType<React.SVGProps<SVGSVGElement>>
    default: IconVariant
    deprecated?: string | boolean
  },
  IconVariant
>

// TODO: Mark icon names as @deprecated in ticket UNI-838.

export type IconNames =
  | 'abSplit'
  | 'accept'
  | 'account'
  | 'active'
  | 'agentCopilot'
  | 'add'
  | 'alicorn'
  | 'audienceGroup'
  | 'analytics'
  | 'annotation'
  | 'array'
  | 'api'
  | 'audiences'
  | 'C360'
  | 'calculatedAttribute'
  | 'catalog'
  | 'chartColumn'
  | 'chartLine'
  | 'check'
  | 'circleNodes'
  | 'close'
  | 'cloud'
  | 'cohort'
  | 'connections'
  | 'conversion'
  | 'criteriaGroup'
  | 'copy'
  | 'dashboard'
  | 'database'
  | 'dataPlatform'
  | 'date'
  | 'delete'
  | 'devices'
  | 'directory'
  | 'dragAndDrop'
  | 'dropdownClose'
  | 'dropdownOpen'
  | 'dsr'
  | 'edit'
  | 'empty'
  | 'enrichment'
  | 'event'
  | 'eventAttribute'
  | 'favorite'
  | 'filter'
  | 'fitToScreen'
  | 'flag'
  | 'folderClosed'
  | 'forwarding'
  | 'fullScreen'
  | 'funnel'
  | 'gear'
  | 'generic'
  | 'grid'
  | 'group'
  | 'heart'
  | 'help'
  | 'helpVideo'
  | 'identity'
  | 'info'
  | 'insights'
  | 'journeyAnalysis'
  | 'journeys'
  | 'jumpTo'
  | 'lightBulb'
  | 'link'
  | 'list'
  | 'liveStream'
  | 'lock'
  | 'logout'
  | 'messageQuestion'
  | 'moreActions'
  | 'mpLogo'
  | 'myHub'
  | 'next'
  | 'notification'
  | 'number'
  | 'notificationSubscribed'
  | 'notificationSubscribe'
  | 'observability'
  | 'openTab'
  | 'organization'
  | 'other'
  | 'otherData'
  | 'oversight'
  | 'overview'
  | 'paywall'
  | 'pause'
  | 'pipelines'
  | 'placeholder'
  | 'play'
  | 'precision'
  | 'predictions'
  | 'premium'
  | 'premiumDt'
  | 'previous'
  | 'privacy'
  | 'privileges'
  | 'refreshFrequency'
  | 'rateDown'
  | 'rateStar'
  | 'rateUp'
  | 'run'
  | 'remove'
  | 'savedProjects'
  | 'scheduledReport'
  | 'search'
  | 'segmentation'
  | 'segmentationAnalysis'
  | 'selected'
  | 'settings'
  | 'setup'
  | 'shieldKeyhole'
  | 'signout'
  | 'siteMap'
  | 'sparkles'
  | 'split'
  | 'string'
  | 'support'
  | 'systemAlerts'
  | 'textWidget'
  | 'timestamp'
  | 'transformation'
  | 'trends'
  | 'unlock'
  | 'upload'
  | 'userAttribute'
  | 'userProfiles'
  | 'users'
  | 'viewOnly'
  | 'wrench'
  | 'zoomIn'
  | 'zoomOut'
  | 'bannerFreemium'
  | 'boolean'
  | 'stateEmpty'
  | 'stateError'
  | 'stateNoResults'
  | 'back'
  | 'submitFeedback'
  | 'boost'
  | 'clone'
  | 'reorder'
  | 'refresh'
