/*
 * This theme is copy/pasted from figma, via the Token Buddy for Ant Design plugin
 *  */

import { type IMpThemeConfig } from 'design/MpThemeConfig'

export const LightTheme: IMpThemeConfig = {
  token: {
    colorLinkHover: '#ab8eff',
    controlOutline: 'rgba(54, 0, 209, 0.1)',
    colorWarningOutline: '#fffbe6',
    colorErrorOutline: '#fff2f0',
    controlItemBgHover: '#f8f6fb',
    controlItemBgActive: '#ebe8f8',
    controlItemBgActiveHover: '#c3aeff',
    colorFill: 'rgba(15, 14, 14, 0.15)',
    colorFillSecondary: 'rgba(32, 0, 122, 0.06)',
    colorFillTertiary: 'rgba(15, 14, 14, 0.04)',
    colorFillQuaternary: 'rgba(32, 0, 122, 0.03)',
    colorBorder: '#c3aeff',
    colorBorderSecondary: '#eceae9',
    colorPrimaryBg: '#f8f6fb',
    colorPrimaryBgHover: '#ebe8f8',
    colorPrimaryBorder: '#c3aeff',
    colorPrimaryBorderHover: '#ab8eff',
    colorPrimaryHover: '#ab8eff',
    colorPrimaryActive: '#8255ff',
    colorPrimaryTextHover: '#5f29f8',
    colorPrimaryText: '#2c00aa',
    colorPrimaryTextActive: '#20007a',
    colorSuccessHover: '#73d13d',
    colorSuccessTextHover: '#237804',
    colorSuccessText: '#135200',
    colorSuccessTextActive: '#092b00',
    colorWarningHover: '#ffc53d',
    colorWarningTextHover: '#ad6800',
    colorWarningText: '#874d00',
    colorWarningTextActive: '#613400',
    colorInfoBg: '#f8f6fb',
    colorInfoBgHover: '#ebe8f8',
    colorInfoBorder: '#c3aeff',
    colorInfoBorderHover: '#ab8eff',
    colorInfoHover: '#ab8eff',
    colorInfoActive: '#8255ff',
    colorInfoTextHover: '#5f29f8',
    colorInfoText: '#2c00aa',
    colorInfoTextActive: '#20007a',
    colorPrimary: '#3600d1',
    colorInfo: '#3600d1',
    fontFamily:
      "'GT America', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, 'Noto Sans', sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'",
    fontFamilyCode: "'Roboto Mono', Consolas, 'Liberation Mono', Menlo, Courier, monospace",
    'mpBrandPrimary.1': '#f8f6fb',
    'mpBrandPrimary.2': '#ebe8f8',
    'mpBrandPrimary.3': '#dbceff',
    'mpBrandPrimary.4': '#c3aeff',
    'mpBrandPrimary.5': '#ab8eff',
    'mpBrandPrimary.6': '#8255ff',
    'mpBrandPrimary.7': '#5f29f8',
    'mpBrandPrimary.8': '#3600d1',
    'mpBrandPrimary.9': '#2c00aa',
    'mpBrandPrimary.10': '#20007a',
    'mpBrandSecondary.1': '#ffffff',
    'mpBrandSecondary.2': '#faf9f8',
    'mpBrandSecondary.3': '#eceae9',
    'mpBrandSecondary.4': '#dcdcd8',
    'mpBrandSecondary.5': '#babbb5',
    'mpBrandSecondary.6': '#717368',
    'mpBrandSecondary.7': '#505249',
    'mpBrandSecondary.8': '#2c2d2b',
    'mpBrandSecondary.9': '#212020',
    'mpBrandSecondary.10': '#0f0e0e',
    mpColorBorderDisabled: '#dcdcd8',
    mpColorIconStrong: '#0f0e0e',
    mpColorIconBrand: '#20007a',
    mpIconSizeXS: 12,
    mpIconSizeSM: 16,
    mpIconSizeMD: 20,
    mpIconSizeLG: 24,
    mpIconSizeXL: 28,
    mpIconSizeXXL: 32,
    mpIconSizeXXXL: 40,
    mpIconSizeXXXXL: 48,
    mpQueryItem_borderWidth: '0 0 1px 0',
    mpQueryItem_borderColor: '#c3aeff',
    mpQueryItem_borderColor_active: '#3600d1',
    mpQueryItem_borderColor_disabled: '#dcdcd8',
    mpQueryItem_borderColor_error: '#f5222d',
    mpQueryItem_bgColor: '#ffffff',
    mpQueryItem_bgColor_hover: '#f8f6fb',
    mpQueryItem_bgColor_active: '#ebe8f8',
    mpQueryItem_bgColor_disabled: '#faf9f8',
    mpQueryItem_borderWidth_active: '0 0 2px 0',
    mpQueryItem_shadow_focus: '0 0 0 2px rgba(54, 0, 209, 0.1)',
    mpQueryItem_color_disabled: '#505249',
    'mpQueryItem|valueSelector_fontWeight': '500',
    'mpQueryItem|valueSelector_color': '#20007a',
    mpQueryItem_padding: 4,
    mpQueryItem_gap: 4,
    mpQueryItem_height: 32,
    mpQueryItem_borderRadius: 2,
    'mpQueryItem|action|primary_color': '#3600d1',
    'mpQueryItem|action|secondary_color': '#505249',
    'mpQueryItem|action_fontWeight': '400',
    mpQueryItem_shadow_active: '0 0 0 2px rgba(54, 0, 209, 0.1)',
    mpQueryItem_shadow: 'none',
    mpQueryItem_borderColor_focus: '#3600d1',
    mpQueryItem_borderColor_hover: '#3600d1',
  },
  components: {
    Steps: {
      colorFillContent: '#dcdcd8',
      colorPrimary: '#2c2d2b',
      controlItemBgActive: '#babbb5',
    },
    Button: {
      borderColorDisabled: '#dcdcd8',
      primaryShadow: '0 2px 0 rgba(54, 0, 209, 0.1)',
      onlyIconSizeLG: 20,
      onlyIconSizeSM: 12,
    },
    Menu: {
      darkItemBg: '#212020',
      darkItemColor: 'rgba(255, 255, 255, 0.65)',
      darkItemDisabledColor: 'rgba(255, 255, 255, 0.25)',
      darkSubMenuItemBg: '#0f0e0e',
      itemHoverBg: '#f8f6fb',
      subMenuItemBg: '#faf9f8',
      darkGroupTitleColor: 'rgba(255, 255, 255, 0.65)',
    },
    Progress: {
      defaultColor: '#2c2d2b',
      remainingColor: '#eceae9',
    },
    Select: {
      multipleItemBg: '#ebe8f8',
      mpColorBorderDisabled: '#dcdcd8',
    },
    Image: {
      previewOperationColor: 'rgba(255, 255, 255, 0.65)',
      previewOperationColorDisabled: 'rgba(255, 255, 255, 0.25)',
      previewOperationHoverColor: 'rgba(255, 255, 255, 0.85)',
    },
    Table: {
      footerBg: '#faf9f8',
      headerBg: '#faf9f8',
      headerSplitColor: 'rgba(0, 0, 0, 0.06)',
      rowSelectedHoverBg: '#ebe8f8',
    },
    Input: {
      activeShadow: '0 0 0 2px rgba(54, 0, 209, 0.1)',
      mpColorBorderDisabled: '#dcdcd8',
    },
    Checkbox: {
      mpColorBorderDisabled: '#dcdcd8',
    },
    Radio: {
      mpColorBorderDisabled: '#dcdcd8',
    },
    DatePicker: {
      mpColorBorderDisabled: '#dcdcd8',
    },
    TimePicker: {
      mpColorBorderDisabled: '#dcdcd8',
    },
    InputNumber: {
      mpColorBorderDisabled: '#dcdcd8',
    },
  },
}
