/*
 * This theme is copy/pasted from figma, via the Token Buddy for Ant Design plugin
 *  */

import { type IMpThemeConfig } from 'design/MpThemeConfig'

export const LightTheme: IMpThemeConfig = {
  token: {
    colorLinkHover: '#ab8eff',
    controlOutline: 'rgba(0.21176470816135406, 0, 0.8196078538894653, 0.1)',
    colorWarningOutline: '#fffbe6',
    colorErrorOutline: '#fff1f0',
    controlItemBgHover: '#f8f6fb',
    controlItemBgActive: '#ebe8f8',
    controlItemBgActiveHover: '#c3aeff',
    colorText: '#0f0e0e',
    colorTextSecondary: '#212020',
    colorTextTertiary: '#2c2d2b',
    colorTextQuaternary: '#505249',
    colorFill: '#dcdcd8',
    colorFillSecondary: '#ebe8f8',
    colorFillTertiary: '#faf9f8',
    colorFillQuaternary: '#f8f6fb',
    colorBgLayout: '#ffffff',
    colorBgSpotlight: '#2c2d2b',
    colorBorder: '#c3aeff',
    colorBorderSecondary: '#eceae9',
    colorSplit: '#eceae9',
    colorPrimaryBg: '#f8f6fb',
    colorPrimaryBgHover: '#ebe8f8',
    colorPrimaryBorder: '#c3aeff',
    colorPrimaryBorderHover: '#ab8eff',
    colorPrimaryHover: '#ab8eff',
    colorPrimaryActive: '#8255ff',
    colorPrimaryTextHover: '#5f29f8',
    colorPrimaryText: '#2c00aa',
    colorPrimaryTextActive: '#20007a',
    colorSuccessHover: '#73d13d',
    colorSuccessTextHover: '#237804',
    colorSuccessText: '#135200',
    colorSuccessTextActive: '#092b00',
    colorWarningHover: '#ffc53d',
    colorWarningTextHover: '#ad6800',
    colorWarningText: '#874d00',
    colorWarningTextActive: '#613400',
    colorErrorBg: '#fff1f0',
    colorErrorBgHover: '#ffccc7',
    colorErrorBorder: '#ffa39e',
    colorErrorBorderHover: '#ff7875',
    colorErrorHover: '#ff4d4f',
    colorErrorActive: '#cf1322',
    colorErrorTextHover: '#a8071a',
    colorErrorText: '#820014',
    colorErrorTextActive: '#5c0011',
    colorBgMask: '#babbb5',
    colorTextBase: '#0f0e0e',
    colorPrimary: '#3600d1',
    colorError: '#f5222d',
    borderRadiusLG: 16,
    borderRadius: 8,
    fontFamily:
      "'GT America', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, 'Noto Sans', sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'",
    fontFamilyCode: "'Roboto Mono', Consolas, 'Liberation Mono', Menlo, Courier, monospace",
    'mpBrandPrimary.1': '#f8f6fb',
    'mpBrandPrimary.2': '#ebe8f8',
    'mpBrandPrimary.3': '#dbceff',
    'mpBrandPrimary.4': '#c3aeff',
    'mpBrandPrimary.5': '#ab8eff',
    'mpBrandPrimary.6': '#8255ff',
    'mpBrandPrimary.7': '#5f29f8',
    'mpBrandPrimary.8': '#3600d1',
    'mpBrandPrimary.9': '#2c00aa',
    'mpBrandPrimary.10': '#20007a',
    'mpBrandSecondary.1': '#fff',
    'mpBrandSecondary.2': '#faf9f8',
    'mpBrandSecondary.3': '#eceae9',
    'mpBrandSecondary.4': '#dcdcd8',
    'mpBrandSecondary.5': '#babbb5',
    'mpBrandSecondary.6': '#717368',
    'mpBrandSecondary.7': '#505249',
    'mpBrandSecondary.8': '#2c2d2b',
    'mpBrandSecondary.9': '#212020',
    'mpBrandSecondary.10': '#0f0e0e',
    mpColorBorderDisabled: '#dcdcd8',
    mpQueryItem_borderWidth: '0 0 1px 0',
    mpQueryItem_borderColor: '#c3aeff',
    mpQueryItem_borderColor_active: '#3600d1',
    mpQueryItem_borderColor_disabled: '#dcdcd8',
    mpQueryItem_borderColor_error: '#f5222d',
    mpQueryItem_bgColor: '#ffffff',
    mpQueryItem_bgColor_hover: '#f8f6fb',
    mpQueryItem_bgColor_active: '#ebe8f8',
    mpQueryItem_bgColor_disabled: '#faf9f8',
    mpQueryItem_borderWidth_active: '0 0 2px 0',
    mpQueryItem_shadow_focus: '0 0 0 2px rgba(54, 0, 209, 0.1)',
    mpQueryItem_color_disabled: '#505249',
    'mpQueryItem|valueSelector_fontWeight': '500',
    'mpQueryItem|valueSelector_color': '#20007a',
    mpQueryItem_padding: 4,
    mpQueryItem_gap: 4,
    mpQueryItem_height: 32,
    mpQueryItem_borderRadius: 2,
    'mpQueryItem|action|primary_color': '#3600d1',
    'mpQueryItem|action|secondary_color': '#505249',
    'mpQueryItem|action_fontWeight': '400',
    mpQueryItem_shadow_active: '0 0 0 2px rgba(54, 0, 209, 0.1)',
    mpQueryItem_shadow: 'none',
    mpQueryItem_borderColor_focus: '#3600d1',
    mpQueryItem_borderColor_hover: '#3600d1',
  },
  components: {
    Steps: {
      colorFillContent: '#dcdcd8',
      colorPrimary: '#2c2d2b',
      controlItemBgActive: '#babbb5',
    },
    Button: {
      borderColorDisabled: '#dcdcd8',
      primaryShadow: '0 2px 0 rgba(54, 0, 209, 0.1)',
      onlyIconSizeLG: 20,
      onlyIconSizeSM: 12,
    },
    Menu: {
      darkItemBg: '#212020',
      darkItemColor: '#babbb5',
      darkItemDisabledColor: '#505249',
      darkSubMenuItemBg: '#0f0e0e',
      itemHoverBg: '#f8f6fb',
      subMenuItemBg: '#faf9f8',
      darkGroupTitleColor: '#babbb5',
    },
    Progress: {
      defaultColor: '#2c2d2b',
      remainingColor: '#eceae9',
    },
    Select: {
      multipleItemBg: '#ebe8f8',
      mpColorBorderDisabled: '#dcdcd8',
    },
    Table: {
      footerBg: '#faf9f8',
      headerBg: '#faf9f8',
      headerSplitColor: '#eceae9',
      rowSelectedHoverBg: '#ebe8f8',
    },
    Input: {
      activeShadow: '0 0 0 2px rgba(54, 0, 209, 0.1)',
      mpColorBorderDisabled: '#dcdcd8',
    },
    Checkbox: {
      mpColorBorderDisabled: '#dcdcd8',
    },
    Radio: {
      mpColorBorderDisabled: '#dcdcd8',
    },
    DatePicker: {
      mpColorBorderDisabled: '#dcdcd8',
    },
    TimePicker: {
      mpColorBorderDisabled: '#dcdcd8',
    },
    InputNumber: {
      mpColorBorderDisabled: '#dcdcd8',
    },
  },
}
