/*
 * This theme is copy/pasted from figma, via the Token Buddy for Ant Design plugin
 *  */

import { type IMpThemeConfig } from 'design/MpThemeConfig'

export const LightTheme: IMpThemeConfig = {
  token: {
    colorText: 'rgba(0, 0, 0, 0.95)',
    colorTextSecondary: 'rgba(0, 0, 0, 0.75)',
    colorTextTertiary: 'rgba(0, 0, 0, 0.55)',
    colorTextQuaternary: 'rgba(0, 0, 0, 0.4)',
    colorBorder: '#FFADD2',
    colorBorderSecondary: '#eceae9',
    colorFill: 'rgba(181, 30, 109, 0.15)',
    colorFillSecondary: 'rgba(181, 30, 109, 0.06)',
    colorFillTertiary: 'rgba(181, 30, 109, 0.04)',
    colorFillQuaternary: 'rgba(181, 30, 109, 0.02)',
    colorPrimary: '#B51E6D',
    colorInfo: '#B51E6D',
    colorInfoBg: '#FFF0F6',
    colorInfoBgHover: '#FFD6E7',
    colorInfoBorder: '#FFADD2',
    colorInfoBorderHover: '#FF85C0',
    colorInfoHover: '#F759AB',
    colorInfoActive: '#9E1068',
    colorInfoTextHover: '#F759AB',
    colorInfoText: '#9E1068',
    colorInfoTextActive: '#780650',
    colorPrimaryBg: '#FFF0F6',
    colorPrimaryBgHover: '#FFD6E7',
    colorPrimaryBorder: '#FFADD2',
    colorPrimaryBorderHover: '#FF85C0',
    colorPrimaryHover: '#F759AB',
    colorPrimaryActive: '#9E1068',
    colorPrimaryTextHover: '#F759AB',
    colorPrimaryText: '#9E1068',
    colorPrimaryTextActive: '#780650',
    controlOutline: 'rgba(181, 30, 109, 0.1)',
    fontFamily: "'GT America', -system-ui, sans-serif",
    fontFamilyCode: '‘Roboto Mono’, monospace',
    fontWeightStrong: 500,
    colorFillAlterSolid: '#FFF0F6',
    colorFilledHandleBg: '#FFD6E7',
    'mpBrandPrimary.1': '#FFF0F6',
    'mpBrandPrimary.2': '#FFD6E7',
    'mpBrandPrimary.3': '#FFADD2',
    'mpBrandPrimary.4': '#FF85C0',
    'mpBrandPrimary.5': '#F759AB',
    'mpBrandPrimary.6': '#EB2F96',
    'mpBrandPrimary.7': '#B51E6D',
    'mpBrandPrimary.8': '#9E1068',
    'mpBrandPrimary.9': '#780650',
    'mpBrandPrimary.10': '#420828',
    'mpBrandSecondary.1': '#ffffff',
    'mpBrandSecondary.2': '#faf9f8',
    'mpBrandSecondary.3': '#eceae9',
    'mpBrandSecondary.4': '#dcdcd8',
    'mpBrandSecondary.5': '#babbb5',
    'mpBrandSecondary.6': '#717368',
    'mpBrandSecondary.7': '#505249',
    'mpBrandSecondary.8': '#2c2d2b',
    'mpBrandSecondary.9': '#212020',
    'mpBrandSecondary.10': '#0f0e0e',
    mpColorIconStrong: '#0f0e0e',
    mpColorIconBrand: '#780650',
    mpColorBorderDisabled: '#dcdcd8',
    mpIconSizeXS: 12,
    mpIconSizeSM: 16,
    mpIconSizeMD: 20,
    mpIconSizeLG: 24,
    mpIconSizeXL: 28,
    mpIconSizeXXL: 32,
    mpIconSizeXXXL: 40,
    mpIconSizeXXXXL: 48,
    mpQueryItem_height: 32,
    mpQueryItem_padding: 4,
    mpQueryItem_gap: 4,
    mpQueryItem_borderWidth: '0 0 1px 0',
    mpQueryItem_borderWidth_active: '0 0 2px 0',
    mpQueryItem_borderRadius: 2,
    mpQueryItem_borderColor: '#FFADD2',
    mpQueryItem_borderColor_focus: '#B51E6D',
    mpQueryItem_borderColor_hover: '#B51E6D',
    mpQueryItem_borderColor_active: '#B51E6D',
    mpQueryItem_borderColor_disabled: '#dcdcd8',
    mpQueryItem_borderColor_error: '#ff4d4f',
    mpQueryItem_bgColor: '#ffffff',
    mpQueryItem_bgColor_hover: '#FFF0F6',
    mpQueryItem_bgColor_active: '#FFD6E7',
    mpQueryItem_bgColor_disabled: 'rgba(15, 14, 14, 0.04)',
    mpQueryItem_color_disabled: 'rgba(0, 0, 0, 0.4)',
    mpQueryItem_shadow: 'none',
    mpQueryItem_shadow_focus: '0 0 0 2px rgba(181, 30, 109, 0.1)',
    mpQueryItem_shadow_active: '0 0 0 2px rgba(181, 30, 109, 0.1)',
    'mpQueryItem|valueSelector_fontWeight': '500',
    'mpQueryItem|valueSelector_color': '#780650',
    'mpQueryItem|action|primary_color': '#B51E6D',
    'mpQueryItem|action|secondary_color': 'rgba(0, 0, 0, 0.55)',
    'mpQueryItem|action_fontWeight': '400',
  },
  components: {
    Steps: {
      colorPrimary: '#2c2d2b',
    },
    Progress: {
      defaultColor: '#2c2d2b',
    },
    Button: {
      borderColorDisabled: '#dcdcd8',
    },
    Input: {
      activeShadow: '0 0 0 2px rgba(181, 30, 109, 0.1)',
      errorActiveShadow: '0 0 0 2px rgba(255, 38, 5, 0.1)',
      warningActiveShadow: '0 0 0 2px rgba(255, 215, 5, 0.2)',
    },
    Cascader: {
      colorHighlight: '#F759AB',
    },
  },
}
