import React, { useState } from 'react'
import { Flex, Form, Icon, Input, Select, Space, Typography } from 'src/components'
import { Tooltip } from 'antd'
import { type Meta, type StoryObj } from '@storybook/react'
import { QuestionCircleOutlined } from '@ant-design/icons'

const meta: Meta<typeof Input> = {
  title: 'Components/Data Entry/Input',
  component: Input,

  args: {
    placeholder: 'Enter text',
    disabled: false,
    maxLength: undefined,
    status: undefined,
    size: 'middle',
    type: 'text',
    addonBefore: undefined,
    allowClear: false,
    value: '',
    onChange: e => {
      console.log('Input changed: ' + e.target.value)
    },
    onPressEnter: e => {
      console.log('Enter key pressed: ' + String(e))
    },
  },

  argTypes: {
    maxLength: {
      control: 'number',
    },
    status: {
      control: 'select',
      options: ['warning', 'error', 'default'],
    },
    size: {
      control: 'select',
      options: ['small', 'medium', 'large'],
    },
  },
}
export default meta

type Story = StoryObj<typeof Input>

/*
  Initial story templates generated by AI.
  Customize the stories based on specific requirements.
*/

const LabelWithTooltip = ({ label, tooltipMessage }: { label: string; tooltipMessage: string | React.ReactNode }) => (
  <Flex align="center" gap={4}>
    <Typography.Text>{label}</Typography.Text>
    <Tooltip title={tooltipMessage}>
      <QuestionCircleOutlined />
    </Tooltip>
  </Flex>
)

export const TextInput: Story = {
  render: () => {
    return (
      <Space direction="vertical" size={4} style={{ maxWidth: 320 }}>
        <Input placeholder="Enter text" type="text" style={{ width: 320 }} />
      </Space>
    )
  },
}

export const NumberInput: Story = {
  render: () => {
    return (
      <Space direction="vertical" size={4} style={{ maxWidth: 320 }}>
        <Input
          id="required-field"
          placeholder="Enter number"
          type="number"
          min={0}
          max={100}
          required
          aria-required
          style={{ width: 320 }}
        />
      </Space>
    )
  },
}

export const PercentageInput: Story = {
  render: () => {
    return (
      <Space direction="vertical" size={4} style={{ maxWidth: 320 }}>
        <Input
          id="percentage-field"
          placeholder="0"
          type="number"
          min={0}
          max={100}
          addonAfter="%"
          style={{ width: 160 }}
        />
      </Space>
    )
  },
}

export const DurationInput: Story = {
  render: () => {
    const [value, setValue] = useState<number>(30)
    const [unit, setUnit] = useState<string>('hours')

    const selectAfter = (
      <Select
        value={unit}
        onChange={setUnit}
        options={[
          { label: 'Minutes', value: 'minutes' },
          { label: 'Hours', value: 'hours' },
          { label: 'Days', value: 'days' },
        ]}
        dropdownMatchSelectWidth={false}
        style={{ width: 100 }}
      />
    )

    return (
      <Space direction="vertical" size={4} style={{ maxWidth: 320 }}>
        <Input
          type="number"
          min={0}
          value={value}
          onChange={e => setValue(Number(e.target.value))}
          addonAfter={selectAfter}
          placeholder="Enter number"
          style={{ width: 200 }}
        />
      </Space>
    )
  },
}

export const SearchInput: Story = {
  render: () => {
    return (
      <Space direction="vertical" size={4} style={{ maxWidth: 320 }}>
        <Input
          placeholder="Search"
          allowClear
          autoFocus
          addonBefore={<Icon name="search" size="sm" color="default" />}
          style={{ width: 320 }}
        />
      </Space>
    )
  },
}

type FieldType = {
  requiredTextInput?: string
  optionalTextInput?: string
  helpTextInput?: string
  warehouseUsername?: string
}

export const RequiredTextInput: Story = {
  render: () => {
    return (
      <Form<FieldType> layout="vertical" style={{ maxWidth: 320 }}>
        <Form.Item<FieldType>
          label="Required Text Input"
          name="requiredTextInput"
          rules={[{ required: true, message: 'Please enter a value.' }]}>
          <Input placeholder="Enter text" style={{ width: 320 }} />
        </Form.Item>
      </Form>
    )
  },
}

export const OptionalInput: Story = {
  render: () => {
    return (
      <Form<FieldType> layout="vertical" style={{ maxWidth: 320 }}>
        <Form.Item<FieldType> label="Optional Text Input" name="optionalTextInput">
          <Input placeholder="Enter text" style={{ width: 320 }} />
        </Form.Item>
      </Form>
    )
  },
}

export const HelpTextInput: Story = {
  render: () => {
    return (
      <Form<FieldType> layout="vertical" style={{ maxWidth: 320 }}>
        <Form.Item<FieldType>
          label={<LabelWithTooltip label="Text Input with Help" tooltipMessage="Helpful description for this input" />}>
          <Input placeholder="Enter text" style={{ width: 320 }} />
        </Form.Item>
      </Form>
    )
  },
}

export const TextAreaInput: Story = {
  render: () => {
    return (
      <Space direction="vertical" size={4} style={{ maxWidth: 320 }}>
        <Input.TextArea placeholder="Share feedback..." maxLength={500} rows={4} style={{ width: 320 }} />
      </Space>
    )
  },
}

export const PasswordInput: Story = {
  render: () => {
    return (
      <Space direction="vertical" size={4} style={{ maxWidth: 320 }}>
        <Input.Password placeholder="Enter password" style={{ width: 320 }} />
      </Space>
    )
  },
}
