import { type Meta, type StoryObj } from '@storybook/react'
import { Badge } from 'src/components/data-display/Badge/Badge'
import { ColorPrimary } from 'src/styles/style'
import { ExampleStory } from 'src/utils/ExampleStory'
import { Space } from 'src/components'

const meta: Meta<typeof Badge> = {
  title: 'Components/Data Display/Badge',
  component: Badge,
}
export default meta

type Story = StoryObj<typeof Badge>

/*
  Initial story templates generated by AI.
  Customize the stories based on specific requirements.
*/

export const DotBadge: Story = {
  args: {
    dot: true,
    color: ColorPrimary,
  },
}

export const StatusBadge: Story = {
  argTypes: {
    status: {
      control: 'select',
      options: ['success', 'processing', 'default', 'error', 'warning'],
    },
  },
  render: () => {
    return (
      <ExampleStory title="Standalone badge with status.">
        <Space>
          <Badge status="success" />
          <Badge status="error" />
          <Badge status="default" />
          <Badge status="processing" />
          <Badge status="warning" />
        </Space>
        <br />
        <Space orientation="vertical">
          <Badge status="success" text="Success" />
          <Badge status="error" text="Error" />
          <Badge status="default" text="Default" />
          <Badge status="processing" text="Processing" />
          <Badge status="warning" text="Warning" />
        </Space>
      </ExampleStory>
    )
  },
}

export const WithText: Story = {
  args: {
    dot: true,
    status: 'success',
    text: 'Active',
  },
}
