import { type Meta, type StoryObj } from '@storybook/react'
import { Badge } from 'src/components/data-display/Badge/Badge'
import { Space } from 'src/components'
import { ColorPrimary, ColorSuccess, ColorWarning, ColorError, ColorBorderSecondary } from 'src/styles/style'

const meta: Meta<typeof Badge> = {
  title: 'Components/Data Display/Badge',
  component: Badge,
}
export default meta

type Story = StoryObj<typeof Badge>

/*
  Initial story templates generated by AI.
  Customize the stories based on specific requirements.
*/

export const DotBadge: Story = {
  render: () => {
    const colors = [
      { label: 'Primary', value: ColorPrimary },
      { label: 'Success', value: ColorSuccess },
      { label: 'Warning', value: ColorWarning },
      { label: 'Error', value: ColorError },
      { label: 'Paused', value: ColorBorderSecondary },
    ] as const

    return (
      <Space wrap size="large">
        {colors.map(({ label, value }) => (
          <Badge dot key={label} color={value} title={label} />
        ))}
      </Space>
    )
  },
}

export const StatusBadge: Story = {
  argTypes: {
    status: {
      control: 'select',
      options: ['success', 'processing', 'default', 'error', 'warning'],
    },
  },
  render: () => {
    return (
      <Space direction="horizontal" wrap size="large">
        <Badge status="success" text="Success" />
        <Badge status="error" text="Error" />
        <Badge status="default" text="Paused" />
        <Badge status="processing" text="Processing" />
        <Badge status="warning" text="Warning" />
      </Space>
    )
  },
}

export const WithText: Story = {
  args: {
    dot: true,
    status: 'success',
    text: 'Active',
  },
}
