import { type Meta, type StoryObj } from '@storybook/react'
import { Avatar, Icon } from 'src/components'

const meta: Meta<typeof Avatar> = {
  title: 'Components/Data Display/Avatar',
  component: Avatar,
}
export default meta

type Story = StoryObj<typeof Avatar>

/*
  Initial story templates generated by AI.
  Customize the stories based on specific requirements.
*/

export const WithInitials: Story = {
  args: {
    children: 'mP',
  },
}

export const WithIcon: Story = {
  args: {
    icon: <Icon name="userProfiles" size="lg" color="white" />,
  },
}
