import { type Meta, type StoryObj } from '@storybook/react'
import { Avatar, Badge, Icon, Space } from 'src/components'
import { ColorWhite, MpBrandSecondary3, MpBrandSecondary4, MpBrandSecondary8, Size } from 'src/styles/style'

const neutralAvatarStyle = { backgroundColor: MpBrandSecondary4, color: MpBrandSecondary8 }
const neutralIconProps = { name: 'userProfiles', size: 'lg' as const, color: ColorWhite }
const spaceSize = parseInt(Size, 10)

const meta: Meta<typeof Avatar> = {
  title: 'Components/Data Display/Avatar',
  component: Avatar,
}
export default meta

type Story = StoryObj<typeof Avatar>

/*
  Initial story templates generated by AI.
  Customize the stories based on specific requirements.
*/

export const ShapeExamples: Story = {
  render: () => {
    return (
      <Space size={spaceSize}>
        <Avatar style={neutralAvatarStyle}>MP</Avatar>
        <Avatar shape="square" style={neutralAvatarStyle}>
          MP
        </Avatar>
      </Space>
    )
  },
}

export const SizeExamples: Story = {
  render: () => {
    return (
      <Space size={spaceSize}>
        <Avatar size="small" style={neutralAvatarStyle}>
          MP
        </Avatar>
        <Avatar style={neutralAvatarStyle}>MP</Avatar>
        <Avatar size="large" style={neutralAvatarStyle}>
          MP
        </Avatar>
      </Space>
    )
  },
}

export const TypePhoto: Story = {
  args: {
    src: 'https://randomuser.me/api/portraits/women/72.jpg',
    alt: 'Avatar with photo',
  },
}

export const TypeIcon: Story = {
  args: {
    style: neutralAvatarStyle,
    icon: <Icon {...neutralIconProps} />,
  },
}

export const TypeInitials: Story = {
  args: {
    children: 'MP',
  },
}

export const WithBadge: Story = {
  render: () => {
    return (
      <Space size={spaceSize}>
        <Badge count={3} size="small">
          <Avatar style={neutralAvatarStyle} icon={<Icon {...neutralIconProps} />} />
        </Badge>
        <Badge dot>
          <Avatar style={neutralAvatarStyle}>MP</Avatar>
        </Badge>
      </Space>
    )
  },
}

export const WithGroup: Story = {
  render: () => {
    const teammates = [
      {
        name: 'Chloe Martinez',
        src: 'https://randomuser.me/api/portraits/women/65.jpg',
      },
      {
        name: 'Ernest Wallace',
        src: 'https://randomuser.me/api/portraits/men/34.jpg',
      },
      {
        name: 'Priya Patel',
        initials: 'PP',
      },
      {
        name: 'Lars Ostergaard',
        initials: 'LO',
      },
    ]

    return (
      <Space direction="vertical" size={spaceSize}>
        <Avatar.Group
          maxCount={3}
          maxPopoverTrigger="click"
          maxPopoverPlacement="bottom"
          maxStyle={{ color: MpBrandSecondary8, backgroundColor: MpBrandSecondary3 }}>
          {teammates.map(teammate => {
            const style = teammate.initials != null ? neutralAvatarStyle : undefined

            return (
              <Avatar key={teammate.name} src={teammate.src} alt={teammate.name} style={style}>
                {teammate.initials}
              </Avatar>
            )
          })}
        </Avatar.Group>
      </Space>
    )
  },
}
