import { type Meta, type StoryObj } from '@storybook/react'
import { Spin } from 'src/components/feedback/Spin/Spin'

const meta: Meta<typeof Spin> = {
  title: 'Components/Feedback/Spin',
  component: Spin,

  args: {
    size: 'default',
  },
  argTypes: {
    size: {
      control: 'select',
      options: ['default', 'small'],
    },
  },
}
export default meta

type Story = StoryObj<typeof Spin>

/*
  Initial story templates generated by AI.
  Customize the stories based on specific requirements.
*/

export const Primary: Story = {}
