import { type Meta, type StoryObj } from '@storybook/react'
import { Descriptions } from 'src/components/data-display/Descriptions/Descriptions'

const meta: Meta<typeof Descriptions> = {
  title: 'Components/Data Display/Descriptions',
  component: Descriptions,

  args: {
    bordered: false,
    colon: true,
    column: 3,
    contentStyle: undefined,
    extra: undefined,
    items: [
      { label: 'Item 1', children: 'Value 1' },
      { label: 'Item 2', children: 'Value 2' },
      { label: 'Item 3', children: 'Value 3' },
    ],
    labelStyle: undefined,
    layout: 'horizontal',
    size: 'default',
    title: undefined,
  },
  argTypes: {
    size: {
      control: 'select',
      options: ['default', 'middle', 'small'],
    },
    layout: {
      control: 'select',
      options: ['horizontal', 'vertical'],
    },
  },
}
export default meta

type Story = StoryObj<typeof Descriptions>

/*
  Initial story templates generated by AI.
  Customize the stories based on specific requirements.
*/

export const Primary: Story = {}
