import { type Meta, type StoryObj } from '@storybook/react'
import { Divider } from 'src/components/layout/Divider/Divider'

const meta: Meta<typeof Divider> = {
  title: 'Components/Layout/Divider',

  component: props => (
    <>
      <span>top text</span>
      <Divider {...props}></Divider>
      <span>bottom text</span>
    </>
  ),

  args: {
    children: 'Divider Title',
    dashed: false,
    titlePlacement: 'center',
    plain: true,
    style: undefined,
    orientation: 'horizontal',
  },

  argTypes: {
    titlePlacement: {
      control: 'select',
      options: ['left', 'right', 'center'],
    },
    orientation: {
      control: 'select',
      options: ['vertical', 'horizontal'],
    },
  },
}
export default meta

type Story = StoryObj<typeof Divider>

/*
  Initial story templates generated by AI.
  Customize the stories based on specific requirements.
*/

export const Primary: Story = {}

export const Dashed: Story = {
  args: {
    dashed: true,
  },
}

export const WithOrientation: Story = {
  args: {
    titlePlacement: 'right',
  },
}

export const WithOrientationMargin: Story = {
  args: {
    titlePlacement: 'left',
  },
}

export const NotPlain: Story = {
  args: {
    plain: false,
  },
}

export const WithStyle: Story = {
  args: {
    style: { color: 'red' },
  },
}

export const VerticalDivider: Story = {
  args: {
    type: 'vertical',
  },
}
