import { type Meta, type StoryObj } from '@storybook/react'
import { InputNumber } from 'src/components/data-entry/InputNumber/InputNumber'

const meta: Meta<typeof InputNumber> = {
  title: 'Components/Data Entry/InputNumber',
  component: InputNumber,

  args: {
    max: Number.MAX_SAFE_INTEGER,
    min: Number.MIN_SAFE_INTEGER,
    placeholder: '',
    autoFocus: false,
    controls: true,
    disabled: false,
    status: undefined,
    size: 'middle',
    decimalSeparator: '.',
    step: 1,
    value: undefined,
    onChange: value => {
      console.log('InputNumber changed: ' + value)
    },
    onPressEnter: e => {
      console.log('Enter key pressed:', e)
    },
    onStep: (value, info) => {
      console.log('Step:', value, info)
    },
  },

  argTypes: {
    autoFocus: {
      control: 'boolean',
    },
    size: {
      control: 'select',
      options: ['large', 'middle', 'small'],
    },
    status: {
      control: 'select',
      options: ['error', 'warning'],
    },
  },
}
export default meta

type Story = StoryObj<typeof InputNumber>

/*
  Initial story templates generated by AI.
  Customize the stories based on specific requirements.
*/

export const Primary: Story = {
  args: {
    max: 90,
    min: 1,
    placeholder: 'number',
    suffix: 'days',
    style: { width: 120, textAlign: 'right' },
  },
}
