import AcceptIcon from 'src/assets/svg/mp_act_lt_accept.svg?react'
import AddIcon from 'src/assets/svg/add.svg?react'
import AlicornIcon from 'src/assets/svg/alicorn.svg?react'
import RateDownIcon from 'src/assets/svg/rate_down.svg?react'
import RateDownIconDt from 'src/assets/svg/mp_act_dt_rate-down.svg?react'
import RateStarIcon from 'src/assets/svg/mp_act_lt_rate-star.svg?react'
import RateStarIconDt from 'src/assets/svg/mp_act_dt_rate-star.svg?react'
import RateUpIcon from 'src/assets/svg/rate_up.svg?react'
import RateUpIconDt from 'src/assets/svg/mp_act_dt_rate-up.svg?react'
import RunIcon from 'src/assets/svg/mp_act_lt_run.svg?react'
import AnalyticsIcon from 'src/assets/svg/mp_pm_lt_analytcis.svg?react'
import AnalyticsIconDt from 'src/assets/svg/mp_pm_dt_analytics.svg?react'
import C360Icon from 'src/assets/svg/mp_pm_lt_c360.svg?react'
import C360IconDt from 'src/assets/svg/mp_pm_dt_c360.svg?react'
import CalculatedAttributeIcon from 'src/assets/svg/mp_info_lt_calculated-attribute.svg?react'
import CriteriaGroupIcon from 'src/assets/svg/mp_info_lt_criteria-group.svg?react'
import CatalogIcon from 'src/assets/svg/mp_pm_lt_catalog.svg?react'
import ChartColumnIcon from 'src/assets/svg/chart-column.svg?react'
import ChartLineIcon from 'src/assets/svg/chart-line.svg?react'
import CheckIcon from 'src/assets/svg/check.svg?react'
import CircleNodesIcon from 'src/assets/svg/circle-nodes.svg?react'
import CloudIcon from 'src/assets/svg/cloud.svg?react'
import ConnectionsIcon from 'src/assets/svg/connections.svg?react'
import DataPlatformIcon from 'src/assets/svg/mp_pm_lt_data-paltform.svg?react'
import DataPlatformIconDt from 'src/assets/svg/mp_pm_dt_data-platform.svg?react'
import DatabaseIcon from 'src/assets/svg/database.svg?react'
import DateIcon from 'src/assets/svg/mp_pm_lt_date.svg?react'
import DevicesIcon from 'src/assets/svg/mp_pm_lt_devices.svg?react'
import DragAndDropIcon from 'src/assets/svg/mp_act_lt_dragandrop.svg?react'
import DsrIcon from 'src/assets/svg/mp_pm_lt_dsr.svg?react'
import EmptyIcon from 'src/assets/svg/empty.svg?react'
import StateError from 'src/assets/svg/mp_info_lt_empty-error.svg?react'
import EnrichmentIcon from 'src/assets/svg/mp_pm_lt_enrichment.svg?react'
import EventAttributeIcon from 'src/assets/svg/event-attribute.svg?react'
import EventIcon from 'src/assets/svg/event.svg?react'
import FitToScreen from 'src/assets/svg/mp_act_lt_fit-to-screen.svg?react'
import FolderClosedIcon from 'src/assets/svg/folder-closed.svg?react'
import ForwardingIcon from 'src/assets/svg/mp_pm_lt_forwarding.svg?react'
import GearIcon from 'src/assets/svg/gear.svg?react'
import GridIcon from 'src/assets/svg/grid.svg?react'
import GroupIcon from 'src/assets/svg/mp_info_lt_group.svg?react'
import HeartIcon from 'src/assets/svg/heart.svg?react'
import HelpIcon from 'src/assets/svg/help.svg?react'
import HistoryIcon from 'src/assets/svg/mp_info_lt_history.svg?react'
import HybridIcon from 'src/assets/svg/mp_info_lt_hybrid.svg?react'
import IdentityIcon from 'src/assets/svg/mp_pm_lt_identity.svg?react'
import JumpToIcon from 'src/assets/svg/mp_act_lt_jump-to.svg?react'
import LightBulbIcon from 'src/assets/svg/lightbulb.svg?react'
import LiveStreamIcon from 'src/assets/svg/mp_pm_lt_live-stream.svg?react'
import MessageQuestionIcon from 'src/assets/svg/message-question.svg?react'
import MpGroupIcon from 'src/assets/svg/mp_info_lt_mp-group.svg?react'
import MpLogoIcon from 'src/assets/svg/mpLogo.svg?react'
import ObservabilityIcon from 'src/assets/svg/mp_pm_lt_observability.svg?react'
import OversightIcon from 'src/assets/svg/mp_pm_lt_oversight.svg?react'
import OversightIconDt from 'src/assets/svg/mp_pm_dt_oversight.svg?react'
import PrecisionIcon from 'src/assets/svg/precision.svg?react'
import PredictionsIcon from 'src/assets/svg/mp_pm_lt_predictions.svg?react'
import PredictionsIconDt from 'src/assets/svg/mp_pm_dt_predictions.svg?react'
import RemoveIcon from 'src/assets/svg/remove.svg?react'
import SearchIcon from 'src/assets/svg/search.svg?react'
import SegmentationIconDt from 'src/assets/svg/mp_pm_dt_segmentation.svg?react'
import ShieldKeyholeIcon from 'src/assets/svg/shield-keyhole.svg?react'
import SignoutIcon from 'src/assets/svg/signout.svg?react'
import SplitIcon from 'src/assets/svg/split.svg?react'
import SystemAlertsIcon from 'src/assets/svg/mp_pm_lt_system-alerts.svg?react'
import TransformationsIcon from 'src/assets/svg/mp_pm_lt_transformations.svg?react'
import UploadIcon from 'src/assets/svg/mp_act_it_upload.svg?react'
import UserAttributeIcon from 'src/assets/svg/user-attribute.svg?react'
import UserIcon from 'src/assets/svg/mp_info_lt_user.svg?react'
import UserProfilesIcon from 'src/assets/svg/mp_pm_lt_userprofiles.svg?react'
import ViewOnlyIcon from 'src/assets/svg/mp_info_lt_view-only.svg?react'
import UsersIcon from 'src/assets/svg/mp_info_lt_users.svg?react'
import WrenchIcon from 'src/assets/svg/wrench.svg?react'
import ZoomIn from 'src/assets/svg/mp_act_lt_zoom-in.svg?react'
import ZoomOut from 'src/assets/svg/mp_act_lt_zoom-out.svg?react'
import PremiumIcon from 'src/assets/svg/mp_info_lt_premium.svg?react'
import PaywallIcon from 'src/assets/svg/mp_info_lt_paywall.svg?react'
import ConversionIcon from 'src/assets/svg/mp_info_lt_conversion.svg?react'
import HelpVideoIcon from 'src/assets/svg/mp_info_lt_help-video.svg?react'
import NextIcon from 'src/assets/svg/mp_act_lt_next.svg?react'
import NumberIcon from 'src/assets/svg/mp_data_lt_number.svg?react'
import OpenTabIcon from 'src/assets/svg/mp_act_lt_open-tab.svg?react'
import PauseIcon from 'src/assets/svg/mp_act_lt_pause.svg?react'
import PlayIcon from 'src/assets/svg/mp_act_lt_play.svg?react'
import PreviousIcon from 'src/assets/svg/mp_act_lt_previous.svg?react'
import DirectoryIcon from 'src/assets/svg/mp_pm_lt_directory.svg?react'
import LockIcon from 'src/assets/svg/mp_act_lt_lock.svg?react'
import UnlockIcon from 'src/assets/svg/mp_act_lt_unlock.svg?react'
import NotificationIcon from 'src/assets/svg/mp_pm_lt_notification.svg?react'
import NotificationSubscribedIcon from 'src/assets/svg/mp_pm_lt_notification_subscribed.svg?react'
import NotificationSubscribeIcon from 'src/assets/svg/mp_pm_lt_notification_subscribe.svg?react'
import PremiumIconDt from 'src/assets/svg/mp_info_dt_premium.svg?react'
import OverviewIcon from 'src/assets/svg/mp_pm_lt_overview.svg?react'
import OverviewIconDt from 'src/assets/svg/mp_pm_dt_overview.svg?react'
import FilterIcon from 'src/assets/svg/mp_act_lt_filter.svg?react'
import ActiveIcon from 'src/assets/svg/mp_info_lt_active.svg?react'
import AgentCopilotIcon from 'src/assets/svg/mp_info_dt_agent-copilot.svg?react'
import AudienceGroupIcon from 'src/assets/svg/mp_info_lt_audience-group.svg?react'
import LinkIcon from 'src/assets/svg/mp_info_link.svg?react'
import InfoIcon from 'src/assets/svg/mp_info_lt_info.svg?react'
import Placeholder from 'src/assets/svg/mp_info_lt_placeholder.svg?react'
import Organization from 'src/assets/svg/mp_pm_lt_organization.svg?react'
import JourneyAnalysis from 'src/assets/svg/mp_pm_lt_journey-analysis.svg?react'
import Dashboard from 'src/assets/svg/mp_pm_lt_dashboard.svg?react'
import Account from 'src/assets/svg/mp_pm_lt_account.svg?react'
import TextWidget from 'src/assets/svg/mp_info_lt_text-widget.svg?react'
import RefreshFrequency from 'src/assets/svg/mp_info_lt_refresh-frequency.svg?react'
import Privileges from 'src/assets/svg/mp_info_lt_privileges.svg?react'
import Funnel from 'src/assets/svg/mp_info_lt_funnel.svg?react'
import Cohort from 'src/assets/svg/mp_info_lt_cohort.svg?react'
import Annotation from 'src/assets/svg/mp_info_lt_annotation.svg?react'
import Delete from 'src/assets/svg/mp_act_lt_delete.svg?react'
import DropdownClose from 'src/assets/svg/mp_act_lt_dropdown-close.svg?react'
import DropdownOpen from 'src/assets/svg/mp_act_lt_dropdown-open.svg?react'
import SegmentationAnalysis from 'src/assets/svg/mp_pm_lt_segmentation-analysis.svg?react'
import ScheduledReport from 'src/assets/svg/mp_pm_lt_scheduled-report.svg?react'
import FullScreen from 'src/assets/svg/mp_act_lt_full-screen.svg?react'
import Edit from 'src/assets/svg/mp_act_lt_edit.svg?react'
import Copy from 'src/assets/svg/mp_act_lt_copy.svg?react'
import MoreActions from 'src/assets/svg/mp_act_lt_more-actions.svg?react'
import AbSplit from 'src/assets/svg/mp_info_lt_ab-split.svg?react'
import ArrayIcon from 'src/assets/svg/mp_data_dt_array.svg?react'
import BannerFreemium from 'src/assets/svg/mp_info_dt_sampled.svg?react'
import BooleanIcon from 'src/assets/svg/mp_data_lt_boolean.svg?react'
import StateEmpty from 'src/assets/svg/mp_info_lt_state-empty.svg?react'
import StateNoResults from 'src/assets/svg/mp_info_lt_state-no-results.svg?react'
import Back from 'src/assets/svg/mp_act_lt_back.svg?react'
import Flag from 'src/assets/svg/flag.svg?react'
import SubmitFeedback from 'src/assets/svg/mp_act_lt_submit-feedback.svg?react'
import Boost from 'src/assets/svg/mp_info_lt_boost.svg?react'
import Clone from 'src/assets/svg/mp_act_lt_clone.svg?react'
import Reorder from 'src/assets/svg/mp_act_lt_reorder.svg?react'
import GenericIcon from 'src/assets/svg/mp_info_lt_generic.svg?react'
import ListIcon from 'src/assets/svg/mp_data_dt_list.svg?react'
import OtherIcon from 'src/assets/svg/mp_info_lt_other.svg?react'
import OtherDataIcon from 'src/assets/svg/mp_data_dt_other.svg?react'
import RefreshIcon from 'src/assets/svg/refresh.svg?react'
import StringIcon from 'src/assets/svg/mp_data_dt_string.svg?react'
import TimestampIcon from 'src/assets/svg/mp_data_dt_timestamp.svg?react'
import ToggleLogicBlocks from 'src/assets/svg/mp_act_lt_toggle-logic-blocks.svg?react'
import MoveToTop from 'src/assets/svg/mp_act_lt_move-to-top.svg?react'
import RegenerateIcon from 'src/assets/svg/mp_act_lt_regenerate.svg?react'

// Rokt icons (from @untitledui/icons)
import {
  HelpCircle as RoktHelpCircle,
  Plus as RoktPlus,
  SearchSm as RoktSearch,
  CheckCircle as RoktCheckCircle,
  ArrowLeft as RoktArrowLeft,
  ArrowRight as RoktArrowRight,
  Tag01 as RoktTag,
  AlertCircle as RoktAlertCircle,
  Announcement02 as RoktAnnouncement,
  ArrowDown as RoktArrowDown,
  Asterisk02 as RoktAsterisk,
  Check as RoktCheck,
  ChevronDown as RoktChevronDown,
  ChevronLeft as RoktChevronLeft,
  ChevronRight as RoktChevronRight,
  ChevronSelectorVertical as RoktChevronSelector,
  Clock as RoktClock,
  CoinsHand as RoktCoinsHand,
  Copy01 as RoktCopy,
  DotsVertical as RoktDotsVertical,
  Edit02 as RoktEdit,
  Eye as RoktEye,
  InfoCircle as RoktInfoCircle,
  LinkExternal01 as RoktLinkExternal,
  Lightbulb02 as RoktLightbulb,
  Mail01 as RoktMail,
  Monitor01 as RoktMonitor,
  PauseCircle as RoktPauseCircle,
  PhoneIncoming01 as RoktPhoneIncoming,
  RefreshCw02 as RoktRefreshCw,
  SearchLg as RoktSearchLg,
  Stars01 as RoktStars,
  Trash01 as RoktTrash,
  User01 as RoktUser,
  X as RoktX,
  XClose as RoktXClose,
  Building05 as RoktBuilding,
  Globe01 as RoktGlobe,
  LayoutAlt01 as RoktLayoutAlt,
  ShoppingCart01 as RoktShoppingCart,
  MarkerPin01 as RoktMarkerPin,
  ZoomIn as RoktZoomIn,
  Image03 as RoktImage,
  MessageChatSquare as RoktMessageChatSquare,
  UserCheck01 as RoktUserCheck,
  Clipboard as RoktClipboard,
  Type01 as RoktType,
  Bold01 as RoktBold,
  Italic01 as RoktItalic,
  Underline01 as RoktUnderline,
  Strikethrough01 as RoktStrikethrough,
  Dotpoints01 as RoktDotpoints,
  Star01 as RoktStar,
  Truck01 as RoktTruck,
  PackageSearch as RoktPackageSearch,
  XCircle as RoktXCircle,
  ReverseLeft as RoktReverseLeft,
  MessageDotsCircle as RoktMessageDotsCircle,
  GitBranch01 as RoktGitBranch,
  GitMerge as RoktGitMerge,
  GitCommit as RoktGitCommit,
  GitPullRequest as RoktGitPullRequest,
  // General
  Activity as RoktActivity,
  Archive as RoktArchive,
  AtSign as RoktAtSign,
  Bookmark as RoktBookmark,
  BookmarkAdd as RoktBookmarkAdd,
  BookmarkCheck as RoktBookmarkCheck,
  BookmarkMinus as RoktBookmarkMinus,
  Building01 as RoktBuilding01,
  Building02 as RoktBuilding02,
  Building04 as RoktBuilding04,
  Equal as RoktEqual,
  EqualNot as RoktEqualNot,
  EyeOff as RoktEyeOff,
  FilterFunnel02 as RoktFilterFunnel,
  Hash02 as RoktHash,
  Heart as RoktHeart,
  LinkExternal02 as RoktLinkExternal02,
  Loading02 as RoktLoading,
  LogIn01 as RoktLogIn,
  LogOut01 as RoktLogOut,
  Minus as RoktMinus,
  SlashCircle01 as RoktSlashCircle,
  Speedometer03 as RoktSpeedometer,
  Target04 as RoktTarget,
  Tool01 as RoktTool,
  CheckSquare as RoktCheckSquare,
  Percent02 as RoktPercent,
  CheckVerified01 as RoktCheckVerified01,
  CheckVerified02 as RoktCheckVerified02,
  Home01 as RoktHome,
  Pin01 as RoktPin,
  Trash03 as RoktTrash03,
  Upload01 as RoktUpload,
  CloudBlank01 as RoktCloudBlank,
  SearchMd as RoktSearchMd,
  Settings01 as RoktSettings,
  Zap as RoktZap,
  DotsGrid as RoktDotsGrid,
  DotsHorizontal as RoktDotsHorizontal,
  Menu01 as RoktMenu,
  Link01 as RoktLink,
  Settings04 as RoktSettings04,
  Share01 as RoktShare,
  Download02 as RoktDownload,
  // Arrows
  ArrowDownLeft as RoktArrowDownLeft,
  ArrowDownRight as RoktArrowDownRight,
  ArrowNarrowDown as RoktArrowNarrowDown,
  ArrowNarrowDownLeft as RoktArrowNarrowDownLeft,
  ArrowNarrowDownRight as RoktArrowNarrowDownRight,
  ArrowNarrowLeft as RoktArrowNarrowLeft,
  ArrowNarrowRight as RoktArrowNarrowRight,
  ArrowNarrowUp as RoktArrowNarrowUp,
  ArrowNarrowUpLeft as RoktArrowNarrowUpLeft,
  ArrowNarrowUpRight as RoktArrowNarrowUpRight,
  ArrowUp as RoktArrowUp,
  ArrowUpLeft as RoktArrowUpLeft,
  ArrowUpRight as RoktArrowUpRight,
  ArrowsDown as RoktArrowsDown,
  ArrowsLeft as RoktArrowsLeft,
  ArrowsRight as RoktArrowsRight,
  ArrowsTriangle as RoktArrowsTriangle,
  ArrowsUp as RoktArrowsUp,
  ChevronDownDouble as RoktChevronDownDouble,
  ChevronLeftDouble as RoktChevronLeftDouble,
  ChevronRightDouble as RoktChevronRightDouble,
  ChevronSelectorHorizontal as RoktChevronSelectorHorizontal,
  ChevronUp as RoktChevronUp,
  ChevronUpDouble as RoktChevronUpDouble,
  CornerDownLeft as RoktCornerDownLeft,
  CornerDownRight as RoktCornerDownRight,
  CornerLeftDown as RoktCornerLeftDown,
  CornerLeftUp as RoktCornerLeftUp,
  CornerRightDown as RoktCornerRightDown,
  CornerRightUp as RoktCornerRightUp,
  CornerUpLeft as RoktCornerUpLeft,
  CornerUpRight as RoktCornerUpRight,
  Expand01 as RoktExpand01,
  Expand06 as RoktExpand06,
  FlipBackward as RoktFlipBackward,
  FlipForward as RoktFlipForward,
  Infinity as RoktInfinity,
  RefreshCcw01 as RoktRefreshCcw01,
  RefreshCcw02 as RoktRefreshCcw02,
  RefreshCcw03 as RoktRefreshCcw03,
  ReverseRight as RoktReverseRight,
  SwitchHorizontal01 as RoktSwitchHorizontal01,
  SwitchHorizontal02 as RoktSwitchHorizontal02,
  SwitchVertical01 as RoktSwitchVertical01,
  SwitchVertical02 as RoktSwitchVertical02,
  // Charts
  BarChart01 as RoktBarChart,
  LineChartDown01 as RoktLineChartDown,
  LineChartUp01 as RoktLineChartUp01,
  LineChartUp02 as RoktLineChartUp02,
  PieChart01 as RoktPieChart,
  TrendDown01 as RoktTrendDown,
  TrendUp01 as RoktTrendUp,
  Translate01 as RoktTranslate,
  // Users
  UserRight01 as RoktUserRight,
  FaceFrown as RoktFaceFrown,
  UserCircle as RoktUserCircle,
  FaceNeutral as RoktFaceNeutral,
  FaceSmile as RoktFaceSmile,
  UserMinus01 as RoktUserMinus,
  Users01 as RoktUsers,
  UserPlus01 as RoktUserPlus,
  // Communication
  Inbox01 as RoktInbox,
  MessageCircle02 as RoktMessageCircle,
  Send01 as RoktSend,
  Mail02 as RoktMail02,
  Mail04 as RoktMail04,
  Mail05 as RoktMail05,
  Phone as RoktPhone,
  Annotation as RoktAnnotation,
  PhoneHangUp as RoktPhoneHangUp,
  MessageChatCircle as RoktMessageChatCircle,
  // Layout
  AlignBottom02 as RoktAlignBottom,
  AlignHorizontalCentre02 as RoktAlignHorizontalCentre,
  AlignLeft02 as RoktAlignLeft02,
  DistributeSpacingVertical as RoktDistributeSpacingVertical,
  Grid01 as RoktGrid,
  IntersectCircle as RoktIntersectCircle,
  LayerSingle as RoktLayerSingle,
  LayersThree01 as RoktLayersThree,
  LayersTwo01 as RoktLayersTwo,
  LayoutRight as RoktLayoutRight,
  LayoutTop as RoktLayoutTop,
  List as RoktList,
  Maximize01 as RoktMaximize,
  Minimize01 as RoktMinimize,
  AlignRight02 as RoktAlignRight02,
  Rows01 as RoktRows,
  AlignVerticalCenter02 as RoktAlignVerticalCenter,
  Columns01 as RoktColumns,
  DistributeSpacingHorizontal as RoktDistributeSpacingHorizontal,
  LayoutGrid01 as RoktLayoutGrid,
  LayoutLeft as RoktLayoutLeft,
  SpacingHeight01 as RoktSpacingHeight01,
  SpacingHeight02 as RoktSpacingHeight02,
  SpacingWidth01 as RoktSpacingWidth01,
  SpacingWidth02 as RoktSpacingWidth02,
  Table as RoktTable,
  // Alerts & feedback
  AlertTriangle as RoktAlertTriangle,
  Cube01 as RoktCube,
  CubeOutline as RoktCubeOutline,
  Bell02 as RoktBell,
  BellOff02 as RoktBellOff,
  NotificationMessage as RoktNotificationMessage,
  ThumbsDown as RoktThumbsDown,
  ThumbsUp as RoktThumbsUp,
  // Media & devices
  Laptop01 as RoktLaptop,
  Lightbulb01 as RoktLightbulb01,
  Play as RoktPlay,
  PlayCircle as RoktPlayCircle,
  Power01 as RoktPower,
  StopCircle as RoktStopCircle,
  Printer as RoktPrinter,
  Microphone01 as RoktMicrophone,
  Recording02 as RoktRecording,
  FastBackward as RoktFastBackward,
  FastForward as RoktFastForward,
  GamingPad01 as RoktGamingPad01,
  GamingPad02 as RoktGamingPad02,
  MicrophoneOff01 as RoktMicrophoneOff,
  Mouse as RoktMouse,
  MusicNote01 as RoktMusicNote,
  Repeat01 as RoktRepeat,
  Rss01 as RoktRss,
  Shuffle01 as RoktShuffle,
  Tv03 as RoktTv,
  VideoRecorder as RoktVideoRecorder,
  VideoRecorderOff as RoktVideoRecorderOff,
  Voicemail as RoktVoicemail,
  VolumeMax as RoktVolumeMax,
  VolumeMin as RoktVolumeMin,
  VolumeMinus as RoktVolumeMinus,
  VolumePlus as RoktVolumePlus,
  VolumeX as RoktVolumeX,
  Headphones01 as RoktHeadphones,
  SkipBack as RoktSkipBack,
  SkipForward as RoktSkipForward,
  Wifi as RoktWifi,
  Phone01 as RoktPhone01,
  Sliders02 as RoktSliders,
  Youtube as RoktYoutube,
  // Shapes
  Stars02 as RoktStars02,
  Stars03 as RoktStars03,
  // Development
  Brackets as RoktBrackets,
  BracketsCheck as RoktBracketsCheck,
  BracketsEllipses as RoktBracketsEllipses,
  BracketsMinus as RoktBracketsMinus,
  BracketsPlus as RoktBracketsPlus,
  BracketsSlash as RoktBracketsSlash,
  BracketsX as RoktBracketsX,
  Browser as RoktBrowser,
  Codepen as RoktCodepen,
  Container as RoktContainer,
  CpuChip02 as RoktCpuChip,
  Database01 as RoktDatabase01,
  Database02 as RoktDatabase02,
  FolderX as RoktFolderX,
  Package as RoktPackage,
  QrCode02 as RoktQrCode,
  Server01 as RoktServer,
  Terminal as RoktTerminal,
  TerminalBrowser as RoktTerminalBrowser,
  Code02 as RoktCode,
  CodeBrowser as RoktCodeBrowser,
  Dataflow01 as RoktDataflow01,
  Dataflow02 as RoktDataflow02,
  TerminalSquare as RoktTerminalSquare,
  Variable as RoktVariable,
  Dataflow04 as RoktDataflow04,
  FileCode01 as RoktFileCode,
  PuzzlePiece01 as RoktPuzzlePiece,
  // Files
  File04 as RoktFile04,
  File05 as RoktFile05,
  FileSearch03 as RoktFileSearch,
  Folder as RoktFolder,
  Paperclip as RoktPaperclip,
  FileCheck03 as RoktFileCheck,
  // Security
  FaceId as RoktFaceId,
  Fingerprint04 as RoktFingerprint,
  Key01 as RoktKey,
  Lock02 as RoktLock,
  LockUnlocked01 as RoktLockUnlocked01,
  LockUnlocked02 as RoktLockUnlocked02,
  PasscodeLock as RoktPasscodeLock,
  ShieldDollar as RoktShieldDollar,
  ShieldOff as RoktShieldOff,
  ShieldTick as RoktShieldTick,
  Shield01 as RoktShield,
  // Finance & eCommerce
  Bank as RoktBank,
  BankNote01 as RoktBankNote,
  CreditCardLock as RoktCreditCardLock,
  CreditCardMinus as RoktCreditCardMinus,
  CreditCardPlus as RoktCreditCardPlus,
  CurrencyEuro as RoktCurrencyEuro,
  CurrencyPound as RoktCurrencyPound,
  CurrencyRuble as RoktCurrencyRuble,
  Sale03 as RoktSale,
  Scales01 as RoktScales,
  Coins04 as RoktCoins,
  CoinsStacked03 as RoktCoinsStacked,
  CreditCardShield as RoktCreditCardShield,
  CurrencyRupee as RoktCurrencyRupee,
  CurrencyYen as RoktCurrencyYen,
  Diamond01 as RoktDiamond,
  ShoppingBag02 as RoktShoppingBag02,
  ShoppingBag03 as RoktShoppingBag03,
  Gift01 as RoktGift,
  Tag03 as RoktTag03,
  CreditCard02 as RoktCreditCard02,
  CreditCardCheck as RoktCreditCardCheck,
  CreditCardDown as RoktCreditCardDown,
  CurrencyDollar as RoktCurrencyDollar,
  PiggyBank02 as RoktPiggyBank,
  Receipt as RoktReceipt,
  ReceiptCheck as RoktReceiptCheck,
  Safe as RoktSafe,
  Wallet04 as RoktWallet,
  // Images
  Camera01 as RoktCamera,
  CameraOff as RoktCameraOff,
  FlashOff as RoktFlashOff,
  Image01 as RoktImage01,
  Flash as RoktFlash,
  // Editor
  AlignCenter as RoktAlignCenter,
  AlignJustify as RoktAlignJustify,
  AlignLeft as RoktAlignLeft,
  AlignRight as RoktAlignRight,
  Attachment01 as RoktAttachment,
  LetterSpacing01 as RoktLetterSpacing,
  LineHeight as RoktLineHeight,
  MagicWand01 as RoktMagicWand,
  RightIndent02 as RoktRightIndent02,
  Move as RoktMove,
  Delete as RoktDelete,
  Dropper as RoktDropper,
  Eraser as RoktEraser,
  PaintPour as RoktPaintPour,
  Palette as RoktPalette,
  ParagraphSpacing as RoktParagraphSpacing,
  ParagraphWrap as RoktParagraphWrap,
  PenTool01 as RoktPenTool,
  Scissors02 as RoktScissors,
  Skew as RoktSkew,
  Brush01 as RoktBrush,
  Figma as RoktFigma,
  Subscript as RoktSubscript,
  CodeSnippet02 as RoktCodeSnippet,
  Hand as RoktHand,
  Heading01 as RoktHeading,
  Perspective01 as RoktPerspective,
  ImageIndentLeft as RoktImageIndentLeft,
  ImageIndentRight as RoktImageIndentRight,
  Pilcrow01 as RoktPilcrow,
  TypeStrikethrough01 as RoktTypeStrikethrough,
  Crop01 as RoktCrop01,
  Crop02 as RoktCrop02,
  Cursor01 as RoktCursor,
  LeftIndent01 as RoktLeftIndent01,
  LeftIndent02 as RoktLeftIndent02,
  RightIndent01 as RoktRightIndent01,
  ZoomOut as RoktZoomOut,
  // Maps & travel
  Bus as RoktBus,
  Car01 as RoktCar,
  Rocket02 as RoktRocket,
  Route as RoktRoute,
  Ticket01 as RoktTicket,
  Compass03 as RoktCompass,
  Flag02 as RoktFlag02,
  Globe06 as RoktGlobe06,
  Luggage01 as RoktLuggage01,
  Luggage02 as RoktLuggage02,
  NavigationPointer01 as RoktNavigationPointer01,
  Train as RoktTrain,
  NavigationPointerOff01 as RoktNavigationPointerOff,
  Map01 as RoktMap01,
  Map02 as RoktMap02,
  Mark as RoktMark,
  Passport as RoktPassport,
  Plane as RoktPlane,
  // Time
  AlarmClock as RoktAlarmClock,
  Hourglass01 as RoktHourglass,
  Calendar as RoktCalendar,
} from '@untitledui/icons'

export {
  AbSplit,
  AcceptIcon,
  Account,
  ActiveIcon,
  AgentCopilotIcon,
  AddIcon,
  AlicornIcon,
  ArrayIcon,
  AudienceGroupIcon,
  RateDownIcon,
  RateDownIconDt,
  RateStarIcon,
  RateStarIconDt,
  RateUpIcon,
  RateUpIconDt,
  RunIcon,
  AnalyticsIcon,
  AnalyticsIconDt,
  Annotation,
  C360Icon,
  C360IconDt,
  CalculatedAttributeIcon,
  CriteriaGroupIcon,
  CatalogIcon,
  ChartColumnIcon,
  ChartLineIcon,
  CheckIcon,
  CircleNodesIcon,
  CloudIcon,
  Cohort,
  ConnectionsIcon,
  ConversionIcon,
  Copy,
  Dashboard,
  DatabaseIcon,
  DataPlatformIcon,
  DataPlatformIconDt,
  DateIcon,
  Delete,
  DevicesIcon,
  DirectoryIcon,
  DragAndDropIcon,
  DropdownClose,
  DropdownOpen,
  DsrIcon,
  Edit,
  EmptyIcon,
  StateError,
  EnrichmentIcon,
  EventAttributeIcon,
  EventIcon,
  FilterIcon,
  FitToScreen,
  Flag,
  FolderClosedIcon,
  ForwardingIcon,
  FullScreen,
  Funnel,
  GearIcon,
  GenericIcon,
  GridIcon,
  GroupIcon,
  HeartIcon,
  HelpIcon,
  HelpVideoIcon,
  HistoryIcon,
  HybridIcon,
  IdentityIcon,
  InfoIcon,
  JourneyAnalysis,
  JumpToIcon,
  LightBulbIcon,
  LinkIcon,
  LiveStreamIcon,
  LockIcon,
  MessageQuestionIcon,
  MoreActions,
  MpGroupIcon,
  MpLogoIcon,
  NextIcon,
  NotificationIcon,
  NotificationSubscribedIcon,
  NotificationSubscribeIcon,
  ObservabilityIcon,
  OpenTabIcon,
  Organization,
  OtherIcon,
  OversightIcon,
  OversightIconDt,
  OverviewIcon,
  OverviewIconDt,
  PauseIcon,
  Placeholder,
  PlayIcon,
  PrecisionIcon,
  PredictionsIcon,
  PredictionsIconDt,
  PremiumIcon,
  PremiumIconDt,
  PreviousIcon,
  Privileges,
  RefreshFrequency,
  Reorder,
  RegenerateIcon,
  RemoveIcon,
  ScheduledReport,
  SearchIcon,
  SegmentationAnalysis,
  SegmentationIconDt,
  ShieldKeyholeIcon,
  SignoutIcon,
  SplitIcon,
  SubmitFeedback,
  SystemAlertsIcon,
  TextWidget,
  TransformationsIcon,
  UnlockIcon,
  UploadIcon,
  UserAttributeIcon,
  UserIcon,
  UserProfilesIcon,
  UsersIcon,
  ViewOnlyIcon,
  WrenchIcon,
  ZoomIn,
  ZoomOut,
  BannerFreemium,
  PaywallIcon,
  StateEmpty,
  StateNoResults,
  Back,
  BooleanIcon,
  Boost,
  Clone,
  ListIcon,
  NumberIcon,
  OtherDataIcon,
  RefreshIcon,
  StringIcon,
  TimestampIcon,
  ToggleLogicBlocks,
  MoveToTop,
  // Rokt icons from @untitledui/icons
  RoktHelpCircle,
  RoktPlus,
  RoktSearch,
  RoktCheckCircle,
  RoktArrowLeft,
  RoktArrowRight,
  RoktTag,
  RoktAlertCircle,
  RoktAnnouncement,
  RoktArrowDown,
  RoktAsterisk,
  RoktCheck,
  RoktChevronDown,
  RoktChevronLeft,
  RoktChevronRight,
  RoktChevronSelector,
  RoktClock,
  RoktCoinsHand,
  RoktCopy,
  RoktDotsVertical,
  RoktEdit,
  RoktEye,
  RoktInfoCircle,
  RoktLinkExternal,
  RoktLightbulb,
  RoktMail,
  RoktMonitor,
  RoktPauseCircle,
  RoktPhoneIncoming,
  RoktRefreshCw,
  RoktSearchLg,
  RoktStars,
  RoktTrash,
  RoktUser,
  RoktX,
  RoktXClose,
  RoktBuilding,
  RoktGlobe,
  RoktLayoutAlt,
  RoktShoppingCart,
  RoktMarkerPin,
  RoktZoomIn,
  RoktImage,
  RoktMessageChatSquare,
  RoktUserCheck,
  RoktClipboard,
  RoktType,
  RoktBold,
  RoktItalic,
  RoktUnderline,
  RoktStrikethrough,
  RoktDotpoints,
  RoktStar,
  RoktTruck,
  RoktPackageSearch,
  RoktXCircle,
  RoktReverseLeft,
  RoktMessageDotsCircle,
  RoktGitBranch,
  RoktGitMerge,
  RoktGitCommit,
  RoktGitPullRequest,
  // General
  RoktActivity,
  RoktArchive,
  RoktAtSign,
  RoktBookmark,
  RoktBookmarkAdd,
  RoktBookmarkCheck,
  RoktBookmarkMinus,
  RoktBuilding01,
  RoktBuilding02,
  RoktBuilding04,
  RoktEqual,
  RoktEqualNot,
  RoktEyeOff,
  RoktFilterFunnel,
  RoktHash,
  RoktHeart,
  RoktLinkExternal02,
  RoktLoading,
  RoktLogIn,
  RoktLogOut,
  RoktMinus,
  RoktSlashCircle,
  RoktSpeedometer,
  RoktTarget,
  RoktTool,
  RoktCheckSquare,
  RoktPercent,
  RoktCheckVerified01,
  RoktCheckVerified02,
  RoktHome,
  RoktPin,
  RoktTrash03,
  RoktUpload,
  RoktCloudBlank,
  RoktSearchMd,
  RoktSettings,
  RoktZap,
  RoktDotsGrid,
  RoktDotsHorizontal,
  RoktMenu,
  RoktLink,
  RoktSettings04,
  RoktShare,
  RoktDownload,
  // Arrows
  RoktArrowDownLeft,
  RoktArrowDownRight,
  RoktArrowNarrowDown,
  RoktArrowNarrowDownLeft,
  RoktArrowNarrowDownRight,
  RoktArrowNarrowLeft,
  RoktArrowNarrowRight,
  RoktArrowNarrowUp,
  RoktArrowNarrowUpLeft,
  RoktArrowNarrowUpRight,
  RoktArrowUp,
  RoktArrowUpLeft,
  RoktArrowUpRight,
  RoktArrowsDown,
  RoktArrowsLeft,
  RoktArrowsRight,
  RoktArrowsTriangle,
  RoktArrowsUp,
  RoktChevronDownDouble,
  RoktChevronLeftDouble,
  RoktChevronRightDouble,
  RoktChevronSelectorHorizontal,
  RoktChevronUp,
  RoktChevronUpDouble,
  RoktCornerDownLeft,
  RoktCornerDownRight,
  RoktCornerLeftDown,
  RoktCornerLeftUp,
  RoktCornerRightDown,
  RoktCornerRightUp,
  RoktCornerUpLeft,
  RoktCornerUpRight,
  RoktExpand01,
  RoktExpand06,
  RoktFlipBackward,
  RoktFlipForward,
  RoktInfinity,
  RoktRefreshCcw01,
  RoktRefreshCcw02,
  RoktRefreshCcw03,
  RoktReverseRight,
  RoktSwitchHorizontal01,
  RoktSwitchHorizontal02,
  RoktSwitchVertical01,
  RoktSwitchVertical02,
  // Charts
  RoktBarChart,
  RoktLineChartDown,
  RoktLineChartUp01,
  RoktLineChartUp02,
  RoktPieChart,
  RoktTrendDown,
  RoktTrendUp,
  RoktTranslate,
  // Users
  RoktUserRight,
  RoktFaceFrown,
  RoktUserCircle,
  RoktFaceNeutral,
  RoktFaceSmile,
  RoktUserMinus,
  RoktUsers,
  RoktUserPlus,
  // Communication
  RoktInbox,
  RoktMessageCircle,
  RoktSend,
  RoktMail02,
  RoktMail04,
  RoktMail05,
  RoktPhone,
  RoktAnnotation,
  RoktPhoneHangUp,
  RoktMessageChatCircle,
  // Layout
  RoktAlignBottom,
  RoktAlignHorizontalCentre,
  RoktAlignLeft02,
  RoktDistributeSpacingVertical,
  RoktGrid,
  RoktIntersectCircle,
  RoktLayerSingle,
  RoktLayersThree,
  RoktLayersTwo,
  RoktLayoutRight,
  RoktLayoutTop,
  RoktList,
  RoktMaximize,
  RoktMinimize,
  RoktAlignRight02,
  RoktRows,
  RoktAlignVerticalCenter,
  RoktColumns,
  RoktDistributeSpacingHorizontal,
  RoktLayoutGrid,
  RoktLayoutLeft,
  RoktSpacingHeight01,
  RoktSpacingHeight02,
  RoktSpacingWidth01,
  RoktSpacingWidth02,
  RoktTable,
  // Alerts & feedback
  RoktAlertTriangle,
  RoktCube,
  RoktCubeOutline,
  RoktBell,
  RoktBellOff,
  RoktNotificationMessage,
  RoktThumbsDown,
  RoktThumbsUp,
  // Media & devices
  RoktLaptop,
  RoktLightbulb01,
  RoktPlay,
  RoktPlayCircle,
  RoktPower,
  RoktStopCircle,
  RoktPrinter,
  RoktMicrophone,
  RoktRecording,
  RoktFastBackward,
  RoktFastForward,
  RoktGamingPad01,
  RoktGamingPad02,
  RoktMicrophoneOff,
  RoktMouse,
  RoktMusicNote,
  RoktRepeat,
  RoktRss,
  RoktShuffle,
  RoktTv,
  RoktVideoRecorder,
  RoktVideoRecorderOff,
  RoktVoicemail,
  RoktVolumeMax,
  RoktVolumeMin,
  RoktVolumeMinus,
  RoktVolumePlus,
  RoktVolumeX,
  RoktHeadphones,
  RoktSkipBack,
  RoktSkipForward,
  RoktWifi,
  RoktPhone01,
  RoktSliders,
  RoktYoutube,
  // Shapes
  RoktStars02,
  RoktStars03,
  // Development
  RoktBrackets,
  RoktBracketsCheck,
  RoktBracketsEllipses,
  RoktBracketsMinus,
  RoktBracketsPlus,
  RoktBracketsSlash,
  RoktBracketsX,
  RoktBrowser,
  RoktCodepen,
  RoktContainer,
  RoktCpuChip,
  RoktDatabase01,
  RoktDatabase02,
  RoktFolderX,
  RoktPackage,
  RoktQrCode,
  RoktServer,
  RoktTerminal,
  RoktTerminalBrowser,
  RoktCode,
  RoktCodeBrowser,
  RoktDataflow01,
  RoktDataflow02,
  RoktTerminalSquare,
  RoktVariable,
  RoktDataflow04,
  RoktFileCode,
  RoktPuzzlePiece,
  // Files
  RoktFile04,
  RoktFile05,
  RoktFileSearch,
  RoktFolder,
  RoktPaperclip,
  RoktFileCheck,
  // Security
  RoktFaceId,
  RoktFingerprint,
  RoktKey,
  RoktLock,
  RoktLockUnlocked01,
  RoktLockUnlocked02,
  RoktPasscodeLock,
  RoktShieldDollar,
  RoktShieldOff,
  RoktShieldTick,
  RoktShield,
  // Finance & eCommerce
  RoktBank,
  RoktBankNote,
  RoktCreditCardLock,
  RoktCreditCardMinus,
  RoktCreditCardPlus,
  RoktCurrencyEuro,
  RoktCurrencyPound,
  RoktCurrencyRuble,
  RoktSale,
  RoktScales,
  RoktCoins,
  RoktCoinsStacked,
  RoktCreditCardShield,
  RoktCurrencyRupee,
  RoktCurrencyYen,
  RoktDiamond,
  RoktShoppingBag02,
  RoktShoppingBag03,
  RoktGift,
  RoktTag03,
  RoktCreditCard02,
  RoktCreditCardCheck,
  RoktCreditCardDown,
  RoktCurrencyDollar,
  RoktPiggyBank,
  RoktReceipt,
  RoktReceiptCheck,
  RoktSafe,
  RoktWallet,
  // Images
  RoktCamera,
  RoktCameraOff,
  RoktFlashOff,
  RoktImage01,
  RoktFlash,
  // Editor
  RoktAlignCenter,
  RoktAlignJustify,
  RoktAlignLeft,
  RoktAlignRight,
  RoktAttachment,
  RoktLetterSpacing,
  RoktLineHeight,
  RoktMagicWand,
  RoktRightIndent02,
  RoktMove,
  RoktDelete,
  RoktDropper,
  RoktEraser,
  RoktPaintPour,
  RoktPalette,
  RoktParagraphSpacing,
  RoktParagraphWrap,
  RoktPenTool,
  RoktScissors,
  RoktSkew,
  RoktBrush,
  RoktFigma,
  RoktSubscript,
  RoktCodeSnippet,
  RoktHand,
  RoktHeading,
  RoktPerspective,
  RoktImageIndentLeft,
  RoktImageIndentRight,
  RoktPilcrow,
  RoktTypeStrikethrough,
  RoktCrop01,
  RoktCrop02,
  RoktCursor,
  RoktLeftIndent01,
  RoktLeftIndent02,
  RoktRightIndent01,
  RoktZoomOut,
  // Maps & travel
  RoktBus,
  RoktCar,
  RoktRocket,
  RoktRoute,
  RoktTicket,
  RoktCompass,
  RoktFlag02,
  RoktGlobe06,
  RoktLuggage01,
  RoktLuggage02,
  RoktNavigationPointer01,
  RoktTrain,
  RoktNavigationPointerOff,
  RoktMap01,
  RoktMap02,
  RoktMark,
  RoktPassport,
  RoktPlane,
  // Time
  RoktAlarmClock,
  RoktHourglass,
  RoktCalendar,
}
