import { type Meta, type StoryObj } from '@storybook/react'
import { Empty } from 'src/components/data-display/Empty/Empty'

const meta: Meta<typeof Empty> = {
  title: 'Components/Data Display/Empty',
  component: Empty,

  args: {
    description: 'No Data',
    image: Empty.PRESENTED_IMAGE_DEFAULT,
    imageStyle: undefined,
  },
}
export default meta

type Story = StoryObj<typeof Empty>

/*
  Initial story templates generated by AI.
  Customize the stories based on specific requirements.
*/

export const Primary: Story = {}
