import { type Meta } from '@storybook/react'
import { type StoryObj } from '@storybook/react'
import { Space } from 'src/components'
import { Tag } from 'src/components/data-display/Tag/Tag'

const meta: Meta<typeof Tag> = {
  title: 'Components/Data Display/Tag',
  component: props => <Tag {...props}>Tag</Tag>,
}
export default meta

type Story = StoryObj<typeof Tag>

/*
  Initial story templates generated by AI.
  Customize the stories based on specific requirements.
*/

export const Primary: Story = {
  args: {
    color: 'default',
    bordered: true,
  },
  argTypes: {
    color: {
      control: 'select',
      options: ['success', 'processing', 'default', 'error', 'warning'],
    },
  },
  render: () => {
    return (
      <Space direction="vertical">
        <Tag color="blue">Prod</Tag>
        <Tag color="purple">Dev</Tag>
        <Tag color="default">Default</Tag>
      </Space>
    )
  },
}
