import { type Meta, type StoryObj } from '@storybook/react'
import { Tooltip } from 'src/components'
import { Button } from 'src/components'

const meta: Meta<typeof Tooltip> = {
  title: 'Components/Data Display/Tooltip',
  component: props => (
    <Tooltip {...props}>
      <Button>Tooltip element</Button>
    </Tooltip>
  ),
}
export default meta

type Story = StoryObj<typeof Tooltip>

export const Primary: Story = {
  args: {
    title: 'Tooltip content',
    placement: 'top',
    trigger: 'hover',
  },
  argTypes: {
    placement: {
      control: 'select',
      options: [
        'top',
        'left',
        'right',
        'bottom',
        'topLeft',
        'topRight',
        'bottomLeft',
        'bottomRight',
        'leftTop',
        'leftBottom',
        'rightTop',
        'rightBottom',
      ],
    },
    trigger: {
      control: 'select',
      options: ['hover', 'focus', 'click', 'contextMenu'],
    },
  },
}

/*
  Initial story templates generated by AI.
  Customize the stories based on specific requirements.
*/
