name: "Dependabot Automerge"

on:
  workflow_dispatch:

jobs:
  automerge-dependabot:
    name: "Automerge Dependabot PR"
    uses: mParticle/mparticle-workflows/.github/workflows/dependabot-automerge.yml@main