name: "Dependabot Branch Rebase"

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  rebase-branch:
    name: "Rebase Development onto Dependabot Branch"
    uses: mParticle/mparticle-workflows/.github/workflows/dependabot-rebase-main.yml@stable
    secrets: inherit